### ISSUE TITLE
국회의원 중에 반송되는 메일입니다. 조치가 필요합니다.

### ISSUE THREAD

**Issue by dalikim** [parti-coop/campaigns#112]
아래 목록이고요. "원인"은 https://docs.aws.amazon.com/ko_kr/ses/latest/DeveloperGuide/notification-contents.html 이 링크를 참조하세요.

이름	메일		 		 		 원인

강길부	shinmut@assembly.go.kr		 Transient::General
김광림	glkim@na.go.kr		 Transient::ContentRejected
김도읍	ldek3525@naver.com		 Undetermined::Undetermined
김석기	7882576kj@hanmail.net		 Transient::General
김성찬	ksc2385@naver.com		 Undetermined::Undetermined
김성태	kst0331@assembly.go.kr		 Transient::General
김중로	kjroffice@naver.com		 Undetermined::Undetermined
김진태	jtkim1013@na.go.kr		 Transient::General
김진표	jp311@assembly.go.kr		 Permanent::General
김태년	ktn0320@daum.net		 Transient::General
김학용	ansung@assembly.go.kr		 Transient::General
김현미	hyunmeek@assembly.go.kr		 Transient::General
나경원	nakw@na.go.kr		 Transient::General
민병두	bdmin1958@assembly.go.kr		 Transient::General
민홍철	hochmin@hanmail.net		 Permanent::General
박경미	parkkm321@naver.com		 Undetermined::Undetermined
박영선	pys21@assembly.go.kr		 Transient::General
박지원	jwp615@hanmail.net		 Transient::General
백재현	jhok100@hanmail.net		 Transient::General
변재일	bji@assembly.go.kr		 Transient::General
서영교	youngkyo2012@naver.com		 Permanent::General
송기헌	peacesong1@naver.com		 Undetermined::Undetermined
송영길	songwin@assembly.go.kr		 Transient::General
송옥주	songok4740@naver.com		 Undetermined::Undetermined
신경민	shinkmin@paran.com		 Permanent::General
심상정	sangjungsim@hanmail.net		 Transient::General
여상규	yeosk@assembly.go.kr		 Transient::General
오신환	oshvictory1@naver.com		 Undetermined::Undetermined
유성엽	yousuoy@hanmail.net		 Transient::General
유승희	337ysh@assembly.go.kr		 Transient::General
윤영일	hwj335@hanmail.net		 Transient::General
윤한홍	7882365@naver.com		 Undetermined::Undetermined
이동섭	nowoncap1@naver.com		 Undetermined::Undetermined
이명수	mslee3@assembly.go.kr		 Transient::General
이용호	614lyh@naver.com		 Undetermined::Undetermined
이원욱	ewon33@hanmail.net		 Transient::MailboxFull
이은재	lej@assembly.go.kr		 Permanent::General
이해찬	lhc21c@assembly.go.kr		 Transient::General
이현재	hanam432@assembly.go.kr		 Transient::General
이혜훈	hhlee@assembly.go.kr		 Transient::General
전해철	sangrokgab@naver.com		 Undetermined::Undetermined
정갑윤	mrjung@assembly.go.kr		 Transient::General
정성호	jsh35351@naver.com		 Undetermined::Undetermined
정세균	skchung@assembly.go.kr		 Transient::ContentRejected
정인화	101bbb@naver.com		 Undetermined::Undetermined
정태옥	okdaegu@naver.com		 Undetermined::Undetermined
조승래	yuseong0413@daum.net		 Transient::General
주광덕	south826@naver.com		 Undetermined::Undetermined
주승용	joo350@hanmail.net		 Transient::General
주호영	7842055@naver.com		 Undetermined::Undetermined
진영	ychin21@assembly.go.kr		 Transient::General
채이배	cyber633@naver.com		 Undetermined::Undetermined
최연혜	choiyeonhye@na.go.kr		 Transient::General
한선교	hansunkyo@assembly.go.kr		 Transient::General
홍문종	mjhong2004@na.go.kr		 Transient::General
홍일표	hip@assembly.go.kr		 Transient::General
황주홍	pv21c@chol.com		 Transient::General
맹성규	withnamdong@naver.com		 Permanent::General
이상헌	leesh_2018@naver.com		 Undetermined::Undetermined
정점식	jsjeong0403@naver.com		 Undetermined::Undetermined

**Comment by wagurano** [comment]
다른 반송 이메일 내용을 확인해봐야겠습니다.
예. 다른 이메일 계정으로 강길부 의원에게 이메일 보낸 결과. 
아래와 같습니다.
<pre>
보내는 사람 이메일: postmaster@assembly.go.kr, 받는 사람 이메일: a*******, 날짜 2019-11-07 11:**:**

이 메세지는 자동 생성된 메일 전송 결과 입니다.
받는 사람 메일주소:shinmut@assembly.go.kr
실패 원인은 아래와 같습니다.

수신측 사용자 계정의 편지함 용량이 부족합니다.
수신측 사용자 계정에 메일을 저장하는데 실패했습니다.
자체 메일서버에서 발생하는 실패 메세지 입니다.

>>shinmut@assembly.go.kr
 
-----The following addresses had permanent fatal errors -----
 
 
>>unable to save: mailbox overflow
</pre>

**Comment by dalikim** [comment]
> 다른 반송 이메일 내용을 확인해봐야겠습니다.
> 예. 다른 이메일 계정으로 강길부 의원에게 이메일 보낸 결과.
> 아래와 같습니다.

일일이 확인해 봐야하는 것일까요? ㅠㅠ

**Comment by wagurano** [comment]
계속 확인해보겠습니다.

**Comment by dalikim** [comment]
> 계속 확인해보겠습니다.

메일 긁어서 모두에게 한 통 발송해 보는 것은 어떨까요?

**Comment by wagurano** [comment]
이메일주소 재확인 필요(사용자 없음)
- 김진표 jp311@assembly.go.kr
- 이은재 lej@assembly.go.kr

수신함 가득 참

김성태 kst0331@assembly.go.kr
김진태 jtkim1013@na.go.kr
김학용 ansung@assembly.go.kr
김현미 hyunmeek@assembly.go.kr
나경원 nakw@na.go.kr
민병두 bdmin1958@assembly.go.kr
박영선 pys21@assembly.go.kr
변재일 bji@assembly.go.kr
송영길 songwin@assembly.go.kr
여상규 yeosk@assembly.go.kr
유승희 337ysh@assembly.go.kr
이동섭 nowoncap1@naver.com
이명수 mslee3@assembly.go.kr
이해찬 lhc21c@assembly.go.kr
이현재 hanam432@assembly.go.kr
이혜훈 hhlee@assembly.go.kr
전해철 sangrokgab@naver.com
정갑윤 mrjung@assembly.go.kr
주호영 7842055@naver.com
진영 ychin21@assembly.go.kr
최연혜 choiyeonhye@na.go.kr
홍문종 mjhong2004@na.go.kr
홍일표 hip@assembly.go.kr

그 외 반송 메일 확인하지 못함

**Comment by dalikim** [comment]
참여연대에서 국회의원에게 일일이 전화해서 확인 중입니다.

**Comment by dalikim** [comment]
https://campaigns.kr/campaigns/251 캠페인에서 21대 국회의원 메일 발송 결과

김정호 더불어민주당 kimjungho3359@daum.net Transient::General
송갑석 더불어민주당 kssong800518@daum.net Transient::General
김은혜 미래통합당 eunhye440@naver.com Permanent::General
송재호 더불어민주당 song.jeju@naver.com Permanent::General
이달곤 미래통합당 dalgon@na.go.kr Permanent::General
이용 미래통합당 yonglee1169@assembly.com Permanent::General
