### ISSUE TITLE
스토리 업데이하면 참여자에게 자동 이메일을 발송합니다.

### ISSUE THREAD

**Issue by gjkimpam** [parti-coop/campaigns#133]
(참여연대 별밤&계정 님 만나서 들었던 아이디어&제안 공유합니다) 

참여자에게 아래 상황에서 자동 이메일이 가거나 카카오톡 알림 등으로 연동할 수 있으면 좋겠어요.
1) 캠페인 참여 즉시
2) 후속 소식 업로드 시

캠페인에 무사히 참여했다는 것을 알리고, 후속 반응을 보내서 캠페인이 끝날때까지 계속 함께할 수 있도록 하는 의도입니다.

**Comment by rest515** [comment]
@dalikim 님. 이 기능은 개발 완료된 건이죠?

**Comment by dalikim** [comment]
네 맞습니다
