### ISSUE TITLE
개인정보 이용 및 수집 동의[필수]로 통합하고, 게시합니다.

### ISSUE THREAD

**Issue by Mee-parti** [parti-coop/campaigns#175]
개인정보 이용 및 수집 동의[필수]와 [선택]으로 따로 만들어져 있습니다. [필수] 항목으로 통합해서 진행되며, [보기]를 눌렀을때 필수 항목과 선택 항목을 한페이지에 보여주도록 합니다.

이후 선택항목(휴대전화번호와 주소)을 추가하는 이벤트 시, 캠페인 참여시점에 "제3자동의"와 "선택"항목 동의를 받아, 한꺼번에 처리할수 있도록 하면 된다고 하네요.

**Comment by dalikim** [comment]
@Mee-parti @iamswain25 @rest515 

1. 고지가 이렇게 바뀝니다. https://github.com/parti-coop/govcraft/commit/ef4bb3753bd38b6ad827f0dbbbcaee0ac38d4a79#diff-69f915f6067baf9505b2069f93cd4b99 

2. must와 option이 통합됨에 따라 현재 동의 상황을 조사했습니다. must는 confirm하고 option을 confirm하지 않은 분은 현재 총 6명입니다.

[["2861210@naver.com", "안균"], ["hellostranger.mm@gmail.com", "moviecoder"], ["ecine999@naver.com", "ecine999"], ["salimhealthcoop@gmail.com", "살림의료복지사협"], ["news@ccej.or.kr", "경실련"], ["swain@parti.xyz", "iamswain"], ["gold881103@gmail.com", "clasico"]]

2-1 고작 6명이니 이분들에게 안내메일 드리고 confirm된 것을 un-confirm으로 되돌려 놓으면 어떨까요? 배포 후에요.

**Comment by Mee-parti** [comment]
좋습니다. 안내메일을 한번더 드리면 좋을 것 같아요.

**Comment by dalikim** [comment]
> 고지 바꿔주셔서 감사하고, 저도 안내메일을 한번더 드리면 되지 않을까해요.

@Mee-parti 위 6분에게 메일로 고지 한 번 부탁드립니다. (iamswain는 @iamswain25 님이신듯)
