### ISSUE TITLE
부트스트랩 4 적용

### ISSUE THREAD

**Issue by rest515** [parti-coop/campaigns#178]

**Comment by iamswain25** [comment]
<img width="1085" alt="스크린샷 2020-05-21 10 59 06" src="https://user-images.githubusercontent.com/15191725/82601600-ab3a9700-9b64-11ea-92bf-ee2f3849ca71.png">

소셜 공유 부분이 조금 깨지네요. 그리고 코드에는 카톡 공유도 있던데, 실서버에서 카톡 버튼은 안나오네요.

**Comment by dalikim** [comment]
실서버 배포했습니다. 우선 완료하고 추가 일감을 잡을까 합니다. 어떠세요? @rest515 @iamswain25
