### ISSUE TITLE
주요 스팸댓글 게시물 관리

### ISSUE THREAD

**Issue by Mee-parti** [parti-coop/campaigns#180]
1. 3개 게시글(소식란)에 스팸댓글이 많다는 걸 파악했습니다. 
- https://campaigns.kr/surveys/42
- https://campaigns.kr/stories/129
- https://wouldyouparty.campaigns.kr/stories/117
admin에서 보고 지웠는데, 막상 페이지를 가면 또 댓글을 지워야 하는 상황도 나타나네요. 3월까지 지우다가 이렇게 하나씩 지워야 하나 해서, 혹시 방법이 있지 않을까 해서 이슈를 남깁니다.

**Comment by iamswain25** [comment]
1. 특정 키워드가 포함되면 입력 안되게 하는 방법
2. 익명 글쓰기를 없애는 방법
