### ISSUE TITLE
파비콘이 보여야합니다

### ISSUE THREAD

**Issue by dalikim** [parti-coop/campaigns#190]

**Comment by rest515** [comment]
@iamswain25 님 확인 부탁드려요.

**Comment by iamswain25** [comment]
ENV에 `RAILS_SERVE_STATIC_FILES`만 추가하면 될 것 같아요. 인프라 코드 배포는 달리님이 README.md 파일에 한 번 정리해주시면 좋겠습니다. @dalikim

**Comment by dalikim** [comment]
네 좋습니다. 다만 저는 가끔 트래픽 로드가 단기간에 집중되는 경향이 있습니다. RAILS_SERVE_STATIC_FILES보다는 파비콘 이미지 링크를 수정하는걸 고려해 보길 제안 드립니다.

**Comment by dalikim** [comment]
그리고 인라프는 가급적 여기 언급하지 않으려 합니다. 이 소스를 오픈소스로 갈때 인프라는 이 소스가 설치되는 환경에 맞추면 좋겠거든요. 그래서 인프라 언급을 최소화하면 하고 지금 생각에 반드시 언급할 인프라가 뭔지 딱히 떠오르지 않네요.
