### ISSUE TITLE
[문의] 촉구 메일의 수신 제목 표기 방식이 변경될까요?

### ISSUE THREAD

**Issue by Kyejeong** [parti-coop/campaigns#204]
촉구 메일을 수신한 대상이 받은 메일 제목 표기 방법의 변경이 가능할까요? 
참여자의 이름을 부각시켜주었으면 해서 변경 방식을 문의드립니다.

현재 수신자 메일함에 표기되는 메일 제목 방식 : ‘캠페인 제목+참여자 이름’

변경 제안하는 메일 제목 방식 : '참여자 이름+(한마디+) 캠페인 제목'

**Comment by rest515** [comment]
이건 이미 적용된 것 같으네요. @dalikim

**Comment by rest515** [comment]
@dalikim 요거 적용된 것 같은데, 확인 한번 부탁드립니다.

**Comment by dalikim** [comment]
@rest515 https://github.com/parti-coop/campaigns/commit/bb610db59ff38cdc322e0dcfad4b6e7aee2e252f#r43433528 여길 보시고 완료 여부를 시스님이 판단해 주세요.

**Comment by rest515** [comment]
네, 작업하신 것 같아서. 확인차 여쭤봤습니다. 그럼 완료처리하겠습니다.
