### ISSUE TITLE
[문의] 참여자의 팻말들기 게시물를 삭제할 수 있을까요? 

### ISSUE THREAD

**Issue by Kyejeong** [parti-coop/campaigns#206]
https://campaigns.kr/campaigns/258/pickets 

빠띠 캠페인즈 팻말들기에서 참여자가 중복으로 올린 사진 중에 1개를 삭제하고 싶습니다. 

관리자 아이디로 로그인했을 때, 관리자가 올린 게시물에는 '삭제' 버튼이 활성화돼 있고 참여자가 올린 게시물에는 '신고' '박제' 버튼만 있습니다. 
참여자는 이름만 등록하고(이메일은 선택사항이라 기입하지 않음) 사진을 게시했다고 합니다. 
문의 관련 사진을 첨부합니다. 

* 관리자 아이디로 로그인해서 올린 팻말들기 게시물
<img width="282" alt="스크린샷 2020-08-31 오후 10 16 46" src="https://user-images.githubusercontent.com/46298150/91724809-cf345c80-ebd8-11ea-80fa-42c91fe21428.png">

* 삭제하고 싶은 게시물 : '게시자 : 김주호 / #기본주거권 실현을 위해 뚜벅뚜벅 활동해 가겠습니다. 세상을 바꾸는 천만걸음에 함께 합니다.' 
<img width="580" alt="스크린샷 2020-08-31 오후 10 16 55" src="https://user-images.githubusercontent.com/46298150/91724921-f1c67580-ebd8-11ea-937c-f07c35937d2b.png">

**Comment by Kyejeong** [comment]
이름을 잘못 올린 게시물이 있습니다. 수정 가능할까요?

* 이름 오타
<img width="288" alt="스크린샷 2020-08-31 오후 10 30 20" src="https://user-images.githubusercontent.com/46298150/91725369-9c3e9880-ebd9-11ea-9450-d05f6bb205ef.png">

**Comment by Kyejeong** [comment]
PC버전에서 '팻말들기' 버튼이 게시물과 겹쳐서 보이지 않습니다. 

* '팻말들기' 버튼 
<img width="1252" alt="스크린샷 2020-08-31 오후 10 33 05" src="https://user-images.githubusercontent.com/46298150/91725697-0eaf7880-ebda-11ea-9118-1ca46feddc42.png">

**Comment by dalikim** [comment]
> https://github.com/parti-coop/campaigns/issues/206#issue-689206767

김주호님 댓글 하나 삭제 했습니다.

> https://github.com/parti-coop/campaigns/issues/206#issuecomment-683779693

뭘로 바꾸면 되는지요?

**Comment by Kyejeong** [comment]
> > [#206 (comment)](https://github.com/parti-coop/campaigns/issues/206#issue-689206767)
> 
> 김주호님 댓글 하나 삭제 했습니다.
> 
> > [#206 (comment)](https://github.com/parti-coop/campaigns/issues/206#issuecomment-683779693)
> 
> 뭘로 바꾸면 되는지요?

김주호 님, 손병국 님 사진을 둘다 삭제 부탁드립니다.

**Comment by Kyejeong** [comment]
1. 관리자 아이디로 팻말들기 게시물을 삭제/수정 가능할까요? 참여자가 잘못 올리거나 했을 때, 수정 방안이 필요해서요. 

2. 참여자가 자신의 사진을 삭제/수정하는 방법은 '이메일'을 남겨놓으면 되는 것일까요?

**Comment by Kyejeong** [comment]
> PC버전에서 '팻말들기' 버튼이 게시물과 겹쳐서 보이지 않습니다.
> 
> * '팻말들기' 버튼
> 
> <img alt="스크린샷 2020-08-31 오후 10 33 05" width="1252" src="https://user-images.githubusercontent.com/46298150/91725697-0eaf7880-ebda-11ea-9118-1ca46feddc42.png">

팻말들기 버튼바와 겹치는 사진이 숫자는 줄었지만, 여전히 한 개 인증샷과 겹치네요. 수정 가능할까요?

![스크린샷 2020-09-01 오전 10 23 28](https://user-images.githubusercontent.com/46298150/91784467-f8d39f00-ec3d-11ea-8941-4d7cb3c8eff1.png)

**Comment by Kyejeong** [comment]
인증샷 문구 수정 부탁드립니다. 

![스크린샷 2020-09-01 오전 11 30 42](https://user-images.githubusercontent.com/46298150/91788270-c8dcc980-ec46-11ea-8c42-542d00e5d5ca.png)

PEOPLE POWER 피플파워 티셔츠는 바로 요것!컬러 2종  : 크림 / 먹색사이즈 3종 :  XS / M / LS 
=> 수정 문구 : PEOPLE POWER 피플파워 티셔츠는 바로 요것! 컬러 2종  : 크림/먹색, 사이즈 3종 :  XS/M/XL

**Comment by Kyejeong** [comment]
> > PC버전에서 '팻말들기' 버튼이 게시물과 겹쳐서 보이지 않습니다.
> > 
> > * '팻말들기' 버튼
> > 
> > <img alt="스크린샷 2020-08-31 오후 10 33 05" width="1252" src="https://user-images.githubusercontent.com/46298150/91725697-0eaf7880-ebda-11ea-9118-1ca46feddc42.png">
> 
> 팻말들기 버튼바와 겹치는 사진이 숫자는 줄었지만, 여전히 한 개 인증샷과 겹치네요. 수정 가능할까요?
> 
> ![스크린샷 2020-09-01 오전 10 23 28](https://user-images.githubusercontent.com/46298150/91784467-f8d39f00-ec3d-11ea-8941-4d7cb3c8eff1.png)

모바일 버전에서도 팻말들기 하반 버튼바와 인증샷이 겹쳐보이네요. 확인 부탁드립니다.

**Comment by dalikim** [comment]
@Kyejeong 수정했습니다. 확인해 보시고 문제 있으면 이야기 주세요.

**Comment by dalikim** [comment]
@Kyejeong 

> * 관리자 아이디로 팻말들기 게시물을 삭제/수정 가능할까요? 참여자가 잘못 올리거나 했을 때, 수정 방안이 필요해서요.

네. 내일까지 관리자 아이디로 삭제할 수 있게는 할께요. 수정은 내부 정책 확인이 필요합니다. 우선은 삭제만 가능하게 할께요.

> * 참여자가 자신의 사진을 삭제/수정하는 방법은 '이메일'을 남겨놓으면 되는 것일까요?

로그인한 참여자의 댓글은 수정가능하지만, 로그인 없이 남긴 댓글은 수정할 수 없습니다. 이것도 내부 정책 확인해서 방법을 강구해 보겠습니다.

**Comment by dalikim** [comment]
아래 수정 완료했습니다.

> 이름을 잘못 올린 게시물이 있습니다. 수정 가능할까요?
> 
> * 이름 오타
> 
> <img alt="스크린샷 2020-08-31 오후 10 30 20" width="288" src="https://user-images.githubusercontent.com/46298150/91725369-9c3e9880-ebd9-11ea-9450-d05f6bb205ef.png">
