### ISSUE TITLE
캠페인별 관리 항목 탭에 "위젯" 탭을 추가합니다

### ISSUE THREAD

**Issue by rest515** [parti-coop/campaigns#211]
현재 제공하는 위젯을 모아서 보여주면 좋겠습니다. @dalikim 님, 혹시 간단하게 어떤 위젯이 가능할지 알려주시면 제가 운영툴에 넣겠습니다.

**Comment by rest515** [comment]
@dongown 외부에 위젯 가이드 나간 문서 공유 부탁드립니다. 그때 누구나데이터랑 공유했던 것 같으네요.

**Comment by dongown** [comment]
@rest515 https://booming-harp-4d4.notion.site/bdc592ee59214ef0ba3e1e0d9b961e04 입니다 :)
