### ISSUE TITLE
캠페인 사용자 페이지별로 서브도메인을 제공합니다.

### ISSUE THREAD

**Issue by rest515** [parti-coop/campaigns#213]

**Comment by dalikim** [comment]
@rest515 organization 별로 서브 도메인을 제공하던 흔적이 있습니다. 참고요.

**Comment by rest515** [comment]
이건 제가 구현해 보겠습니다. 제 생각엔 도메인을 통해 캠페인즈에 들어오더라도 서브도메인을 계속 유지할 필요는 없고, 다만 링크만 잘 퍼트릴 수 있도록 해드리면 어떨까 싶습니다.
