### ISSUE TITLE
캠페인즈 소식 등록 오류

### ISSUE THREAD

**Issue by dalikim** [parti-coop/campaigns#226]
https://campaigns.kr/campaigns/257/stories 브리타 필터 캠페인에서 소식을 올리려고 하는데 계속 에러가 난다고 하네요. 제가 테스트해볼 수가 없어서 일단 공유해요.

**Comment by dalikim** [comment]
@ssinkjung 긴급 조치가 필요한지요? 내일 오전까지 확인해도 될런지요?

**Comment by ssinkjung** [comment]
오늘 오전까지 확인해주셔도 됩니다!

**Comment by dalikim** [comment]
@ssinkjung 등록할 때 혹시 발행일자를 넣지 않으시고 입력하셨나요? 발행일자 없이 입력 가능하게 할지 고민이네요.

**Comment by ssinkjung** [comment]
> @ssinkjung 등록할 때 혹시 발행일자를 넣지 않으시고 입력하셨나요?( 발행일자 없이 입력 가능하게 할지 고민이네요.)

금자님이 입력하셨는데, 한번 여쭤볼까요?

**Comment by dalikim** [comment]
> > @ssinkjung 등록할 때 혹시 발행일자를 넣지 않으시고 입력하셨나요?( 발행일자 없이 입력 가능하게 할지 고민이네요.)
> 
> 금자님이 입력하셨는데, 한번 여쭤볼까요?

네 부탁드립니다.
