### ISSUE TITLE
빠띠 캠페인즈에서 21대 국회의원 촉구메일 캠페인을 진행하고 있습니다. 그런데, 촉구메일을 수신 못하는 의원이 있다고 합니다. 

### ISSUE THREAD

**Issue by Kyejeong** [parti-coop/campaigns#233]
[국회는 사법농단 법관 탄핵소추하세요!📢](https://campaigns.kr/campaigns/301)

촉구메일 수신 리스트 또는 메일 차단된 리스트를 확인할 수 있을까요?

**Comment by Kyejeong** [comment]
@dalikim

**Comment by dalikim** [comment]
메일 전송에 오류가 있었는데 모니터링을 놓치고 있었습니다. 발송 시작하고 주말 즈음 다시 보고 드리겠습니다.

**Comment by Kyejeong** [comment]
확인주셔서 고맙습니다! 
메일 전송 오류 이유는 무엇일까요.  확인되면 공유 부탁드려요. 메일 차단 리스트도 확인 부탁드리겠습니다.

**Comment by dalikim** [comment]
전송 오류의 원인은 기능을 추가하면서 발생한 소프트웨어 버그입니다. 죄송합니다.

**Comment by Kyejeong** [comment]
수고 많으세요!!!
빠띠 캠페인즈를 사용하면서 늘 감사한 마음뿐입니다!

**Comment by Kyejeong** [comment]
[국회는 사법농단 법관 탄핵소추하세요!📢](https://campaigns.kr/campaigns/301)

문의드려요. 촉구메일 수신 리스트 또는 메일 차단된 리스트를 확인해보셨을까요? @dalikim

**Comment by dalikim** [comment]
["김석기", "국민의힘", "7882576kj@hanmail.net", "Bounce", "Transient::General"],
 ["김진표", "더불어민주당", "jp311@assembly.go.kr", "Bounce", "Permanent::General"],
 ["김태년", "더불어민주당", "ktn0320@daum.net", "Bounce", "Transient::General"],
 ["김태흠", "국민의힘", "ktheum@hanmail.net", "Bounce", "Transient::General"],
 ["노웅래", "더불어민주당", "wraenoh@hanmail.net", "Bounce", "Transient::General"],
 ["민홍철", "더불어민주당", "hochmin@hanmail.net", "Bounce", "Transient::General"],
 ["박성중", "국민의힘", "sjpark101@hanmail.net", "Bounce", "Transient::General"],
 ["박완주", "더불어민주당", "lasco21@hanmail.net", "Bounce", "Transient::General"],
 ["송석준", "국민의힘", "icheonsarang734@assembly.co.kr", "Bounce", "Transient::General"],
 ["위성곤", "더불어민주당", "wishjeju@hanmail.net", "Bounce", "Transient::General"],
 ["이태규", "국민의당", "ltk635@gmail.com", "Bounce", "Transient::MailboxFull"],
 ["인재근", "더불어민주당", "ijgalso@hanmail.net", "Bounce", "Transient::General"],
 ["임이자", "국민의힘", "llj11@hanmail.net", "Bounce", "Transient::General"],
 ["정운천", "국민의힘", "gbs2008@daum.net", "Bounce", "Transient::General"],
 ["조경태", "국민의힘", "yeskt@hanmail.net", "Bounce", "Transient::General"],
 ["조승래", "더불어민주당", "yuseong0413@daum.net", "Bounce", "Transient::General"],
 ["홍문표", "국민의힘", "mphonglove@hanmail.net", "Bounce", "Transient::General"],
 ["김정호", "더불어민주당", "kimjungho3359@daum.net", "Bounce", "Transient::General"],
 ["송갑석", "더불어민주당", "kssong800518@daum.net", "Bounce", "Transient::General"],
 ["강대식", "국민의힘", "mpnib2018@naver.com", "Bounce", "Permanent::General"],
 ["김남국", "더불어민주당", "lawmaker0415@daum.net", "Bounce", "Transient::General"],
 ["김은혜", "국민의힘", "eunhye440@naver.com", "Bounce", "Permanent::General"],
 ["송영길", "더불어민주당", "songwin@assembly.go.kr", "Bounce", "Transient::General"],
 ["우원식", "더불어민주당", "reform1-1@hanmail.net", "Bounce", "Transient::General"],
 ["임종성", "더불어민주당", "5321tempia@hanmail.net", "Bounce", "Transient::General"],
 ["홍영표", "더불어민주당", "youngvote@hanmail.net", "Bounce", "Transient::General"],
 ["송재호", "더불어민주당", "song.jeju@naver.com", "Bounce", "Permanent::General"],
 ["이수진", "더불어민주당", "leesj545@hanmail.net", "Bounce", "Transient::General"],
 ["이용", "국민의힘", "yonglee1169@assembly.com", "Bounce", "Permanent::General"],
 ["임오경", "더불어민주당", "lok0415@hanmail.net", "Bounce", "Transient::General"]



* Transient::General
  * 수신자의 이메일 공급자가 반송했습니다. 나중에 메시지 반송의 원인이 해결될 경우 같은 수신자에게 이메일을 보낼 수 있습니다.
  * 자동 응답 규칙(예: "out of the office" 메시지)이 활성화된 수신자에게 이메일을 보낼 경우 이러한 유형의 알림을 받을 수 있습니다. 
* Permanent::General
  * 영구적인 문제로 인해 수신자에게 이메일이 전달되지 않았습니다만, 수신자의 이메일 공급자가 원인을 명시하지 않았습니다. 몇 가지 일반적인 이유는 다음과 같습니다.  
    * 잘못된 이메일 주소
    * 수신자 도메인이 존재하지 않는 경우 
    * 수신자 이메일 서버가 전달을 차단한 경우 
* Transient::MailboxFull
   * 수신자의 받은 편지함이 꽉 찼기 때문에 수신자의 이메일 공급자가 반송했습니다. 나중에 받은 편지함이 비워지면 같은 수신자에게 이메일을 보낼 수 있습니다.

**Comment by Kyejeong** [comment]
확인해주셔서 고맙습니다! 
리스트로 보여지는 30명 말고, 나머지 국회의원 270명은 모두 촉구메일을 수신했다는 것으로 이해하면 되는 것일까요? @dalikim

**Comment by dalikim** [comment]
네 발송되었습니다만 꽤 늦게 발송된 것으로 추정됩니다. 기존에 발송이 밀려 있던 것 부터 순차 발송되었습니다

**Comment by Kyejeong** [comment]
아하~그렇군요! 
[국회는 사법농단 법관 탄핵소추하세요!📢](https://campaigns.kr/campaigns/301) 촉구메일 캠페인은 2/4 종료했습니다. 
'꽤 늦게 발송 된 것으로 추정'이라고 표현하셨는데, 그렇다면 정확히 언제부터 발송된(국회의원이 수신한) 것인지 확인하기는 어렵다는 것일까요? 
정확히 확인하기 어렵다면, 캠페인 종료 전 기간에 발송된 것인지라도 알 수 있을까요?

캠페인 의제의 담당 부서(사법감시센터)와 상황을 공유해야해서 여쭤봅니다. 번거로운 부탁을 드려 송구합니다. @dalikim
