### ISSUE TITLE
참여연대 캠페이즈 참여인원수 오류 및 촉구하기 오류 확인요청

### ISSUE THREAD

**Issue by sshony** [parti-coop/campaigns#234]
참여연대 박영민님이 chain에게 텔레그램으로 개별적으로 물어본 내용 전달드려요. 
https://campaigns.kr/campaigns/301/orders
1. 첫번째 사진에 656명 인원수와 두번째 사진에 시민330분 인원수 차이가 나는 것이 궁금하다고 해요.
![photo_2021-01-27 14 09 55](https://user-images.githubusercontent.com/58158305/105955937-633c1e80-60ba-11eb-84d4-6e690d8e3bce.jpeg)
![photo_2021-01-27 14 09 58](https://user-images.githubusercontent.com/58158305/105955945-66370f00-60ba-11eb-8958-471a18581062.jpeg)
2. 의원들에게 촉구하기에서 의원들에게 메일이 안가고 있다고 합니다.

**Comment by dalikim** [comment]
@sshony 속도 때문에 캐시를 하는 중이라 카운트가 차이 납니다. 천천히 개선해 보려 합니다. 그리고 촉구하기 메일은 오류가 있었네요. 복구 했습니다.
