### ISSUE TITLE
촉구메일을 캠페이너가 받아볼 수 있으면 좋겠습니다. 또는 테스트 메일을 보내서 확인해볼 수 있을까요?

### ISSUE THREAD

**Issue by Kyejeong** [parti-coop/campaigns#236]
안녕하세요. 참여연대 이계정입니다. 
빠띠 캠페인즈 플랫폼을 제공해주셔서 고맙습니다! 

저희가 빠띠 캠페인즈 촉구메일 액션을 자주 사용하는데요. 촉구 대상이 촉구 메일을 어떻게 받고 있는지 궁금하더라고요. 촉구 메일을 촉구대상이 받을 때 함께 받아볼 수 있을까요? 그게 어렵다면, 촉구 대상이 메일을 어떤 형태로 받고 있게 되는지 테스트 메일로 확인할 수 있는 방법이 있을까요? @dalikim @rest515

**Comment by wagurano** [comment]
아래와 같이 구현할 수 있습니다. 구현 방법에 대해 하나를 선택해주세요. 
1. 기존 메일 발송 기능을 활용합니다.
    1. 수신자에 캠페이너를 추가합니다.
    1. 참조에 캠페이너를 추가합니다.
    1. 숨은 참조에 캠페이너를 추가합니다.
1. 임시 저장하듯이, 메일 미리 보기 화면을 제공합니다.
1. 캠페이너에게만 예시 메일 발송 기능을 추가합니다.

**Comment by Kyejeong** [comment]
반가운 소식을 전해주셔서 고맙습니다. 테스트 메일을 볼 수 있는 기능을  작업 중이라고 이해하면 될까요? @dalikim

**Comment by human109** [comment]
@Kyejeong 

매일 한통씩 받아볼 수 있는 기능을 추가했습니다.
아래 스크린샷과 같이 [촉구관리]에서 기능을 활성화시키고 메일주소를 입력해주시기 바랍니다.

![image](https://user-images.githubusercontent.com/14979273/111748183-8c677700-88d3-11eb-9da3-86703f8dbf62.png)

**Comment by dalikim** [comment]
@Kyejeong 더 진행 상황 없으면 닫을께요. 제안 감사합니다. @rest515 @jjuwoo

**Comment by Kyejeong** [comment]
> @Kyejeong 더 진행 상황 없으면 닫을께요. 제안 감사합니다. @rest515 @jjuwoo

제안을 실행해주셔서 진심으로 고맙습니다! @dalikim
