### ISSUE TITLE
테스트로 개설한 페이지를 삭제할 수 있을까요? 

### ISSUE THREAD

**Issue by Kyejeong** [parti-coop/campaigns#238]
테스트 해보기 위해 페이지를 개설했는데요. 삭제할 수 있을까요? [테스트 페이지](https://campaigns.kr/campaigns/305) @dalikim

**Comment by human109** [comment]
로그인 하신 후 [관리]-[캠페인 종료하기]-[캠페인 삭제] 가 가능합니다.

**Comment by Kyejeong** [comment]
확인했습니다! 고맙습니다^^ @dalikim
