### ISSUE TITLE
서명하기, 팻말들기 등 참여자의 정보는 이름/이메일 수집만 가능한 것일까요?

### ISSUE THREAD

**Issue by Kyejeong** [parti-coop/campaigns#239]
캠페인의 후속 소식을 메시지로도 보낼 수 있도록 참여자의 정보에서 이름/이메일 외에 전화번호도 선택할 수 있는 기능이 있을까요? @dalikim

**Comment by human109** [comment]
서명하기의  경우 [관리]-[상세 설정]-[연락처 입력] 에서  필수 입력/선택 입력 설정이 가능합니다. (개인 정보 설정 체크 필수!)

**Comment by Kyejeong** [comment]
아하 네! 그러면 팻말들기에서는 이름(혹은 별명) / 이메일(선택)만 가능한 것일까요? @dalikim

**Comment by dalikim** [comment]
> 아하 네! 그러면 팻말들기에서는 이름(혹은 별명) / 이메일(선택)만 가능한 것일까요? @dalikim

네 맞습니다. 현재는 그러네요.
