### ISSUE TITLE
루비 버전을 업그레이드합니다.

### ISSUE THREAD

**Issue by rest515** [parti-coop/campaigns#243]
현재 루비 버전이 2.5 대인데요.

최소 2.7 혹은 3.0도 고려해서 업그레이드하는게 어떨까요?

**Comment by dalikim** [comment]
https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.ruby 

beanstalk platform 기본을 쓰고 있는데요. 현재 준비된건 ruby3.0은 없네요. 2.7은 어때요?

**Comment by rest515** [comment]
2.7 좋습니다.

**Comment by dalikim** [comment]
@human109 어사인 드려봤는데요. 토요일 이야기 더 나누시죠.

**Comment by human109** [comment]
네 알겠습니다.
