### ISSUE TITLE
데이터베이스 처음 구성할 때 스키마 로드 실행 중 오류 발생 원인을 확인합니다.

### ISSUE THREAD

**Issue by wagurano** [parti-coop/campaigns#246]
캠페인즈를 처음 개발할 사람들을 위한 가이들 위해 샘플 데이터를 활용하지 않고 초기화하는 방법이 필요합니다. readme 참고하여 실행하였습니다.

    rails db:schema:load

실행 결과 아래와 같은 오류가 발생하였습니다.

<pre>
...
-- add_foreign_key("sent_requests", "agents")
rails aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Referencing column 'agent_id' and referenced column 'id' in foreign key constraint 'fk_rails_aba66e7cf8' are incompatible.: ALTER TABLE `sent_requests` ADD CONSTRAINT `fk_rails_aba66e7cf8`
FOREIGN KEY (`agent_id`)
  REFERENCES `agents` (`id`)
campaigns/db/schema.rb:1358:in `block in <top (required)>'
campaigns/db/schema.rb:13:in `<top (required)>'
campaigns/bin/rails:9:in `require'
campaigns/bin/rails:9:in `<top (required)>'
campaigns/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
Mysql2::Error: Referencing column 'agent_id' and referenced column 'id' in foreign key constraint 'fk_rails_aba66e7cf8' are incompatible.
campaigns/db/schema.rb:1358:in `block in <top (required)>'
campaigns/db/schema.rb:13:in `<top (required)>'
campaigns/bin/rails:9:in `require'
campaigns/bin/rails:9:in `<top (required)>'
campaigns/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)
</pre>

schema.rb 파일 내용

```
  create_table "wikis", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC" do |t|
    t.string   "title"
    t.text     "body",                  limit: 65535
    t.integer  "user_id",                                         null: false
    t.integer  "project_id",                                      null: false
    t.integer  "views_count",                         default: 0
    t.integer  "comments_count",                      default: 0
    t.integer  "likes_count",                         default: 0
    t.datetime "created_at",                                      null: false
    t.datetime "updated_at",                                      null: false
    t.integer  "anonymous_likes_count",               default: 0
    t.index ["project_id"], name: "index_wikis_on_project_id", using: :btree
    t.index ["user_id"], name: "index_wikis_on_user_id", using: :btree
  end

  add_foreign_key "sent_requests", "agents"
  add_foreign_key "sent_requests", "users"
  add_foreign_key "signer_emails", "campaigns"
  add_foreign_key "signer_emails", "users"
end
```

**Update 2021-02-20**
* 오류 발생 원인
  * 로컬 환경: MySQL 8.0
  * sent_requests 테이블의 agent_id 데이터 타입은 int 이고 agents 테이블의 id 타입은 big int 입니다. 타입이 서로 달라서 오류가 발생하였습니다.
* 개선 사항
  * MySQL 버전을 5.7을 사용합니다.
* README 파일에서 MySQL 버전 안내 문구를 수정합니다.

**Comment by human109** [comment]
README 안내 적용했습니다.
