### ISSUE TITLE
[페이지 기능 변경 문의] '추모하기'로 페이지를 '목소리 모으기+인증샷 모으기'로 변경 가능할까요?

### ISSUE THREAD

**Issue by Kyejeong** [parti-coop/campaigns#247]
안녕하세요. 참여연대 이계정입니다. 

🎗노란리본은 [ ]를 위한 [약속입니다](https://campaigns.kr/campaigns/155/pickets) 이 페이지를 2019년에 개설했고, 2020년에도 활용했습니다. 2021년에도 계속 페이지를 운영하고 싶은데요. 처음 개설할 때 '추모하기'를 선택했기 때문에 글쓰기만 가능해요. 올해는 인증샷도 받고 싶은데요. 기존 페이지에 인증샷 추가하는 것이 가능할까요?

**Comment by Kyejeong** [comment]
@dalikim

**Comment by dalikim** [comment]
@Kyejeong 변경해 보았습니다. @human109 @wagurano

**Comment by Kyejeong** [comment]
사진 파일 기능을 추가해주셔서 고맙습니다! @dalikim
