### ISSUE TITLE
첫 페이지 중 캐시되는 영역 안에서 참여자 수 표시가 실제 참여자 수와 차이가 커서 오류처럼 보입니다.

### ISSUE THREAD

**Issue by dalikim** [parti-coop/campaigns#248]

**Comment by dalikim** [comment]
두루뭉실한 숫자 표현을 써보면 어떨까 싶습니다. 예를 들어 "347명"이면 "+300명" 이렇게요.

**Comment by human109** [comment]
좋은 것 같습니다. + 라는 표현보다 이상 이라고 하면 어떨까요?

**Comment by dalikim** [comment]
> 좋은 것 같습니다. + 라는 표현보다 이상 이라고 하면 어떨까요?

네 좋습니다. 적용 부탁드립니다.
