### ISSUE TITLE
[캠페인관리] 데이터 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by sblee2006** [parti-coop/campaigns#264]
@dalikim 

캠페인관리 > 데이터 내려받기
https://campaigns.kr/campaigns/323/edit#tab_data

에서 '의견참여데이터'는 다운로드가 되는데, 
'촉구참여데이터'는 다운로드가 안됩니다

**Comment by dalikim** [comment]
@sblee2006 수정되었습니다. 불편을 드려 죄송합니다.
