### ISSUE TITLE
지도 목소리 모으기에서 이미지 입력은 옵션입니다.

### ISSUE THREAD

**Issue by Kyejeong** [parti-coop/campaigns#270]
안녕하세요. 참여연대 이계정입니다. 

팻말들기 캠페인에 대해 문의드릴게 있습니다. 

[내가 꿈꾸는 세상은?](https://campaigns.kr/campaigns/327/picket)

여기에서 주소 입력칸에 아주 상세하게 적어야 게시가 되던데요. 문의와 의견이 있습니다. 

문의 : 주소 입력값은 어느 정도까지 적어야 게시되는 것일까요?

의견 : 캠페이너가 주소 입력값의 내용을 캠페이너가 동까지 적는 것으로 선택할 수 있을까요? 예를 들면, 00시 00구 00동까지

@dalikim

**Comment by Kyejeong** [comment]
> 안녕하세요. 참여연대 이계정입니다.
> 
> 팻말들기 캠페인에 대해 문의드릴게 있습니다.
> 
> [내가 꿈꾸는 세상은?](https://campaigns.kr/campaigns/327/picket)
> 
> 여기에서 주소 입력칸에 아주 상세하게 적어야 게시가 되던데요. 문의와 의견이 있습니다.
> 
> 문의 : 주소 입력값은 어느 정도까지 적어야 게시되는 것일까요?
> 
> 의견 : 캠페이너가 주소 입력값의 내용을 캠페이너가 동까지 적는 것으로 선택할 수 있을까요? 예를 들면, 00시 00구 00동까지
> 
> @dalikim

제가 다시 '팻말들기'를 해보니 주소 입력창에서 '동'까지만 써도 게시되더라고요. 문의 내용이 해결됐습니다. 죄송합니다.

**Comment by Kyejeong** [comment]
다른 문의가 있어요. 

'팻말들기'에서 '파일 선택'이 필수값이던데요. 혹시 선택값으로 바꾸는 것이 가능한 것일까요? @dalikim 
![스크린샷 2021-04-01 오후 2 00 02](https://user-images.githubusercontent.com/46298150/113245815-abfa9880-92f2-11eb-9cc8-642b4af8f310.png)

**Comment by dalikim** [comment]
@human109 @wagurano 지도 목소리 모을 때는 사진이 없어도 될까요? 어떻게 생각하시는지요? @Kyejeong

**Comment by Kyejeong** [comment]
> @human109 @wagurano 지도 목소리 모을 때는 사진이 없어도 될까요? 어떻게 생각하시는지요? @Kyejeong

참고로 저희가 아바즈 캠페인을 보고 같은 형식으로 개설했어요. 여기에는 우편번호는 필수, 사진이 선택사항이더라고요.[https://secure.avaaz.org/campaign/kr/our_voice_and_stories/](url)
참여연대 회원을 대상으로 진행하는 캠페인인데 사진이 있으면 좋겠지만, 이미지 올리는 것을 하지 못하거나 부담스러워하는 분들이 있어서요.

**Comment by Kyejeong** [comment]
페이지는 4/5부터 참여연대 전체 회원에게 메시지를 발송할 예정이에요. 그래서 오늘 미리 오픈해서 테스트해보고 있어요. 
그런데, 오류가 발생하는 여러가지 사례가 발견돼서 여쭤봅니다. [이전에 개설했던 팻말들기 페이지](https://campaigns.kr/campaigns/312/pickets)에서도 비슷한 사례가 있었거든요.

오류 사례
- 주소를 동까지 썼을 경우, 업로드 실패(모바일, PC)
- 사진파일을 올렸는데 업로드 실패(모바일, PC)
@dalikim

**Comment by dalikim** [comment]
> 페이지는 4/5부터 참여연대 전체 회원에게 메시지를 발송할 예정이에요. 그래서 오늘 미리 오픈해서 테스트해보고 있어요.
> 그런데, 오류가 발생하는 여러가지 사례가 발견돼서 여쭤봅니다. [이전에 개설했던 팻말들기 페이지](https://campaigns.kr/campaigns/312/pickets)에서도 비슷한 사례가 있었거든요.
> 
> 오류 사례 => 등록하기 안됨
> 
> * 주소를 동까지 썼을 경우, 업로드 실패(모바일, PC)
> * 사진파일을 올렸는데 업로드 실패(모바일, PC)
>   @dalikim

오류난 페이지 모습을 발생 시간과 함께 캡쳐해서 주실 수 있을런지요?

**Comment by Kyejeong** [comment]
> > 페이지는 4/5부터 참여연대 전체 회원에게 메시지를 발송할 예정이에요. 그래서 오늘 미리 오픈해서 테스트해보고 있어요.
> > 그런데, 오류가 발생하는 여러가지 사례가 발견돼서 여쭤봅니다. [이전에 개설했던 팻말들기 페이지](https://campaigns.kr/campaigns/312/pickets)에서도 비슷한 사례가 있었거든요.
> > 오류 사례 => 등록하기 안됨
> > 
> > * 주소를 동까지 썼을 경우, 업로드 실패(모바일, PC)
> > * 사진파일을 올렸는데 업로드 실패(모바일, PC)
> >   @dalikim
> 
> 오류난 페이지 모습을 발생 시간과 함께 캡쳐해서 주실 수 있을런지요?

오류 발생 기기와 페이지 모습에 대해서는 확인해달라고 했는데요. 오류 발생 시간이 필요한 이유는 무엇일까요? @dalikim

**Comment by dalikim** [comment]
> > > 페이지는 4/5부터 참여연대 전체 회원에게 메시지를 발송할 예정이에요. 그래서 오늘 미리 오픈해서 테스트해보고 있어요.
> > > 그런데, 오류가 발생하는 여러가지 사례가 발견돼서 여쭤봅니다. [이전에 개설했던 팻말들기 페이지](https://campaigns.kr/campaigns/312/pickets)에서도 비슷한 사례가 있었거든요.
> > > 오류 사례 => 등록하기 안됨
> > > 
> > > * 주소를 동까지 썼을 경우, 업로드 실패(모바일, PC)
> > > * 사진파일을 올렸는데 업로드 실패(모바일, PC)
> > >   @dalikim
> > 
> > 
> > 오류난 페이지 모습을 발생 시간과 함께 캡쳐해서 주실 수 있을런지요?
> 
> 오류 발생 기기와 페이지 모습에 대해서는 확인해달라고 했는데요. 오류 발생 시간이 필요한 이유는 무엇일까요? @dalikim

로그를 보기 위함입니다. 조금 귀찮으시죠? :)

**Comment by Kyejeong** [comment]
https://docs.google.com/spreadsheets/d/1HHExbcRRohUIgB-x7BGyPkoJxLfQtkCnc-jhsusJK1k/edit#gid=0 빠띠 캠페인즈 팻말들기 오류 메시지 기록 시트를 만들고 권한 공유했습니다. @dalikim

**Comment by dalikim** [comment]
네 현재 리포트된 것은 로봇으로 오인되어 일어나는 일 같습니다. https://www.google.com/recaptcha/about/ 좀더 살펴 보죠.

**Comment by Kyejeong** [comment]
확인해주셔서 고맙습니다! @dalikim 저희도 오류 사항이 있으면 구글시트에 기록하겠습니다.

**Comment by dalikim** [comment]
@Kyejeong 커뮤니케이션 혼선을 줄이기 위해 하나의 게시물에서 하나의 문제만 다루려 합니다. 이 이슈는 "지도 목소리 모으기에서 이미지 입력을 옵션으로" 하는 것만 다루고 닫겠습니다. 적용되었고 검토 부탁드립니다. @human109 @wagurano

**Comment by Kyejeong** [comment]
> @Kyejeong 커뮤니케이션 혼선을 줄이기 위해 하나의 게시물에서 하나의 문제만 다루려 합니다. 이 이슈는 "지도 목소리 모으기에서 이미지 입력을 옵션으로" 하는 것만 다루고 닫겠습니다. 적용되었고 검토 부탁드립니다. @human109 @wagurano

이미지 입력을 옵션으로 수정한 기능을 확인했습니다. 고맙습니다! @dalikim 앞으로 '문제'는 한 개씩 여쭤보고 확인하는 방식으로 글을 남기겠습니다. 사용방법을 알려주셔서 고맙습니다.

**Comment by dalikim** [comment]
> > @Kyejeong 커뮤니케이션 혼선을 줄이기 위해 하나의 게시물에서 하나의 문제만 다루려 합니다. 이 이슈는 "지도 목소리 모으기에서 이미지 입력을 옵션으로" 하는 것만 다루고 닫겠습니다. 적용되었고 검토 부탁드립니다. @human109 @wagurano
> 
> 이미지 입력을 옵션으로 수정한 기능을 확인했습니다. 고맙습니다! @dalikim 앞으로 '문제'는 한 개씩 여쭤보고 확인하는 방식으로 글을 남기겠습니다. 사용방법을 알려주셔서 고맙습니다.

아 감사합니다. 제가 제안드린 사용방법을 받아들여 주신 것도 감사합니다. :)
