### ISSUE TITLE
팻말 참여자의 연락처를 받을 수 있게 설정

### ISSUE THREAD

**Issue by Kyejeong** [parti-coop/campaigns#282]
안녕하세요. 참여연대 이계정입니다. 

빠띠 캠페인즈에서 캠페인을 만들 때, 참여자의 정보 수집을 선택할 수 있을까요? 
예전에는 이름, 이메일, 전화번호를 선택할 수 있었던 것으로 기억하는데요...기능이 변경된 것일까요? @dalikim @jsy@pspd.org @kdh@pspd.org @sblee@pspd.org

**Comment by dalikim** [comment]
> 안녕하세요. 참여연대 이계정입니다.
> 
> 빠띠 캠페인즈에서 캠페인을 만들 때, 참여자의 정보 수집을 선택할 수 있을까요?
> 예전에는 이름, 이메일, 전화번호를 선택할 수 있었던 것으로 기억하는데요...기능이 변경된 것일까요? @dalikim @[jsy@pspd.org](mailto:jsy@pspd.org) @[kdh@pspd.org](mailto:kdh@pspd.org) @[sblee@pspd.org](mailto:sblee@pspd.org)

캠페인을 만드는 과정이 복잡하면 접근성이 떨어지더라고요. 간단하게 만들고 난 후 관리 화면에서 말씀하신 설정을 수행할 수 있습니다.

**Comment by Kyejeong** [comment]
팻말들기를 테스트로 만들어봤는데, 관리화면에서 참여자 정보 설정(이름, 이메일, 전화번호) 값을 못찾았어요. https://campaigns.kr/campaigns/358/ @dalikim

**Comment by Kyejeong** [comment]
![Uploading 스크린샷 2021-05-13 오후 1.53.15.png…]()
@dalikim

**Comment by Kyejeong** [comment]
![스크린샷 2021-05-13 오후 1 53 15](https://user-images.githubusercontent.com/46298150/118079373-0eb37980-b3f3-11eb-8417-35f574f6523f.png)
@dalikim

**Comment by dalikim** [comment]
네 팻말들기에는 아직 미지원이예요. 고려해 볼께요

**Comment by Kyejeong** [comment]
![스크린샷 2021-05-13 오후 2 02 22](https://user-images.githubusercontent.com/46298150/118079870-e8daa480-b3f3-11eb-864c-a3ad7928c6c4.png)
![스크린샷 2021-05-13 오후 2 01 46](https://user-images.githubusercontent.com/46298150/118079875-ebd59500-b3f3-11eb-9e69-1b0a10788582.png)
촉구하기와 서명하기를 테스트로 만들었는데요. 서명하기에만 참여자 정보의 개인설정이 있더라고요. @dalikim

**Comment by dalikim** [comment]
네 의도된 바는 아니고요. 필요에 따라 우선 적용된게 서명이죠. 고려해 보겠습니다. @rest515

**Comment by Kyejeong** [comment]
> 네 의도된 바는 아니고요. 필요에 따라 우선 적용된게 서명이죠. 고려해 보겠습니다. @rest515

 답변 고맙습니다! 저희가 캠페인(서명하기, 촉구하기, 목소리 모으기 등)을 개설할 때, 참여자의 전화번호를 기입하도록 하고자해서 여쭤봤습니다. @dalikim 촉구하기, 목소리 모으기의 관리자 화면에 상세설정 기능이 추가되면 공유 부탁드립니다.

**Comment by dalikim** [comment]
> > 네 의도된 바는 아니고요. 필요에 따라 우선 적용된게 서명이죠. 고려해 보겠습니다. @rest515
> 
> 답변 고맙습니다! 저희가 캠페인(서명하기, 촉구하기, 목소리 모으기 등)을 개설할 때, 참여자의 전화번호를 기입하도록 하고자해서 여쭤봤습니다. @dalikim 촉구하기, 목소리 모으기의 관리자 화면에 상세설정 기능이 추가되면 공유 부탁드립니다.

@wagurano 모든 캠페인이 아니고 우선 팻말에만 적용하면 어떠려나요? 캠페인 중에 서명과 팻말만 참여자 상세 정보를 받는 식으로요. @rest515

**Comment by Kyejeong** [comment]
오호~캠페인 팻말 기능을 업데이트해주셨군요. 고맙습니다! 

한가지 여쭤볼 게 있는데요. Commenter Phone => '전화번호'라고 한글로 쓰지 않고, 영어로 써놓은 이유가 있을까요? 
![스크린샷 2021-05-31 오후 1 18 23](https://user-images.githubusercontent.com/46298150/120139304-22dce080-c213-11eb-96d0-a5ae3fd25ab1.png) @dalikim

**Comment by Kyejeong** [comment]
저희가 내일(6/3) 캠페인즈 페이지를 오픈하려고 해요. [https://campaigns.kr/campaigns/363/](url)

참여 팝업창에 여쭤볼 게 있는데요. 아래 사항이 가능할까요?
1. 이메일(필수)
2. 사진(선택)
3. Commenter Phone => '전화번호' 명칭 수정
![120139304-22dce080-c213-11eb-96d0-a5ae3fd25ab1](https://user-images.githubusercontent.com/46298150/120421224-dcb58780-c3a0-11eb-8b70-5672a5e5fe5f.png)

**Comment by Kyejeong** [comment]
> 저희가 내일(6/3) 캠페인즈 페이지를 오픈하려고 해요. [https://campaigns.kr/campaigns/363/](url)
> 
> 참여 팝업창에 여쭤볼 게 있는데요. 아래 사항이 가능할까요?
> 
> 1. 이메일(필수)
> 2. 사진(선택)
> 3. Commenter Phone => '전화번호' 명칭 수정
>    ![120139304-22dce080-c213-11eb-96d0-a5ae3fd25ab1](https://user-images.githubusercontent.com/46298150/120421224-dcb58780-c3a0-11eb-8b70-5672a5e5fe5f.png)
>    @dalikim

안녕하세요. 저희가 페이지 오픈일을 6/7(월)로 연기됐습니다. 주말 사이, 문의한 것에 대해 답변을 받을 수 있을까요? @dalikim

**Comment by dalikim** [comment]
@Kyejeong 늦었네요. 적용된 것 확인 부탁드리고요. "목소리 모으기 + 인증샷 모으기"를 "목소리 모으기"로 강제 변경해서 이미지 업로드는 옵션으로 바꾸었습니다.

**Comment by Kyejeong** [comment]
수정된 내용 확인했습니다! 고맙습니다! @dalikim
