### ISSUE TITLE
촉구메일 발송 주기를 확인 부탁드립니다.

### ISSUE THREAD

**Issue by Kyejeong** [parti-coop/campaigns#293]
안녕하세요. 참여연대 이계정입니다.

촉구메일의 발송 주기를 아래와 같이 2가지 경우로 안내 받았습니다.
1) 촉구 100건 정도 쌓이면 촉구 대상별로 묶어서 발송
2) 촉구건수가 채 100건이 쌓이지는 않았지만 메일 발송한지 2시간이 지나면 그간에 쌓인 촉구를 묶어 발송

현재 진행하는 캠페인의 촉구메일을 샘플로 받고 있는데요. 안내해주신 발송 주기 중에서 2)경우가 반영되고 있는지 궁금합니다. 
촉구하기 캠페인 [국회는 중소상인 코로나19 피해지원금 확대하라!](https://campaigns.kr/campaigns/394)

샘플 메일을 받는 주소 : webmaster@pspd.org

7/8부터 받은 샘플 메일 리스트는 캡쳐 이미지를 첨부합니다. 
![스크린샷 2021-07-12 오후 7 09 33](https://user-images.githubusercontent.com/46298150/125271396-ab3bbe80-e345-11eb-8d3c-7e042f83a529.png)
7/8부터 오늘(7/12)까지 총 7통의 샘플 메일을 받았습니다. @dalikim

**Comment by dalikim** [comment]
네 확인하고 연락드릴게요.
감사합니다

달리ㅣ활동가
Democracy Activist Dali Kim
더 민주적인 세상, 빠띠 parti.coop

**Comment by Kyejeong** [comment]
촉구 캠페인의 샘플 메일이 7/13 이후 전달되지 않고 있어요. 어떤 상황인지 궁금해서 연락드려요. @dalikim 
![스크린샷 2021-07-15 오후 8 13 42](https://user-images.githubusercontent.com/46298150/125779184-20f23087-0a03-4b1a-a684-6d7e715408c2.png)

**Comment by dalikim** [comment]
> 촉구 캠페인의 샘플 메일이 7/13 이후 전달되지 않고 있어요. 어떤 상황인지 궁금해서 연락드려요. @dalikim
> ![스크린샷 2021-07-15 오후 8 13 42](https://user-images.githubusercontent.com/46298150/125779184-20f23087-0a03-4b1a-a684-6d7e715408c2.png)

이런이런 ㅠㅠ 오늘 샘플 메일 발송이 되는지 확인해 주시겠어요?

**Comment by dalikim** [comment]
> 안녕하세요. 참여연대 이계정입니다.
> 
> 촉구메일의 발송 주기를 아래와 같이 2가지 경우로 안내 받았습니다.
> 
> 1. 촉구 100건 정도 쌓이면 촉구 대상별로 묶어서 발송
> 2. 촉구건수가 채 100건이 쌓이지는 않았지만 메일 발송한지 2시간이 지나면 그간에 쌓인 촉구를 묶어 발송
> 
> 현재 진행하는 캠페인의 촉구메일을 샘플로 받고 있는데요. 안내해주신 발송 주기 중에서 2)경우가 반영되고 있는지 궁금합니다.
> 촉구하기 캠페인 [국회는 중소상인 코로나19 피해지원금 확대하라!](https://campaigns.kr/campaigns/394)
> 
> 샘플 메일을 받는 주소 : [webmaster@pspd.org](mailto:webmaster@pspd.org)
> 
> 7/8부터 받은 샘플 메일 리스트는 캡쳐 이미지를 첨부합니다.
> ![스크린샷 2021-07-12 오후 7 09 33](https://user-images.githubusercontent.com/46298150/125271396-ab3bbe80-e345-11eb-8d3c-7e042f83a529.png)
> 7/8부터 오늘(7/12)까지 총 7통의 샘플 메일을 받았습니다. @dalikim

그리고 샘플 메일은 캠페인 마다 하루에 딱 한 통만 발행되어요.

**Comment by Kyejeong** [comment]
> > 안녕하세요. 참여연대 이계정입니다.
> > 촉구메일의 발송 주기를 아래와 같이 2가지 경우로 안내 받았습니다.
> > 
> > 1. 촉구 100건 정도 쌓이면 촉구 대상별로 묶어서 발송
> > 2. 촉구건수가 채 100건이 쌓이지는 않았지만 메일 발송한지 2시간이 지나면 그간에 쌓인 촉구를 묶어 발송
> > 
> > 현재 진행하는 캠페인의 촉구메일을 샘플로 받고 있는데요. 안내해주신 발송 주기 중에서 2)경우가 반영되고 있는지 궁금합니다.
> > 촉구하기 캠페인 [국회는 중소상인 코로나19 피해지원금 확대하라!](https://campaigns.kr/campaigns/394)
> > 샘플 메일을 받는 주소 : [webmaster@pspd.org](mailto:webmaster@pspd.org)
> > 7/8부터 받은 샘플 메일 리스트는 캡쳐 이미지를 첨부합니다.
> > ![스크린샷 2021-07-12 오후 7 09 33](https://user-images.githubusercontent.com/46298150/125271396-ab3bbe80-e345-11eb-8d3c-7e042f83a529.png)
> > 7/8부터 오늘(7/12)까지 총 7통의 샘플 메일을 받았습니다. @dalikim
> 
> 그리고 샘플 메일은 캠페인 마다 하루에 딱 한 통만 발행되어요.

아하 그렇군요! 
그러면, 7월 10일과 7월 11일에 샘플메일을 2통 받은 것은 어떤 상황일까요? @dalikim

**Comment by Kyejeong** [comment]
> > 촉구 캠페인의 샘플 메일이 7/13 이후 전달되지 않고 있어요. 어떤 상황인지 궁금해서 연락드려요. @dalikim
> > ![스크린샷 2021-07-15 오후 8 13 42](https://user-images.githubusercontent.com/46298150/125779184-20f23087-0a03-4b1a-a684-6d7e715408c2.png)
> 
> 이런이런 ㅠㅠ 오늘 샘플 메일 발송이 되는지 확인해 주시겠어요?

수요일(7/14), 오늘(7/15) 받은 샘플 메일이 없습니다. @dalikim

**Comment by dalikim** [comment]
> > > 촉구 캠페인의 샘플 메일이 7/13 이후 전달되지 않고 있어요. 어떤 상황인지 궁금해서 연락드려요. @dalikim
> > > ![스크린샷 2021-07-15 오후 8 13 42](https://user-images.githubusercontent.com/46298150/125779184-20f23087-0a03-4b1a-a684-6d7e715408c2.png)
> > 
> > 
> > 이런이런 ㅠㅠ 오늘 샘플 메일 발송이 되는지 확인해 주시겠어요?
> 
> 수요일(7/14), 어제(7/15), 오늘(7/16) 받은 샘플 메일이 없습니다. @dalikim

계속 발송되고 있고 최근에 2021-07-19 16:44:47 발송된 것으로 나옵니다. 샘플 메일은 계속 나가지 않고 있나요?

**Comment by Kyejeong** [comment]
> > > > 촉구 캠페인의 샘플 메일이 7/13 이후 전달되지 않고 있어요. 어떤 상황인지 궁금해서 연락드려요. @dalikim
> > > > ![스크린샷 2021-07-15 오후 8 13 42](https://user-images.githubusercontent.com/46298150/125779184-20f23087-0a03-4b1a-a684-6d7e715408c2.png)
> > > 
> > > 
> > > 이런이런 ㅠㅠ 오늘 샘플 메일 발송이 되는지 확인해 주시겠어요?
> > 
> > 
> > 수요일(7/14), 어제(7/15), 오늘(7/16) 받은 샘플 메일이 없습니다. @dalikim
> 
> 계속 발송되고 있고 최근에 2021-07-19 16:44:47 발송된 것으로 나옵니다. 샘플 메일은 계속 나가지 않고 있나요?
7월 14일부터 샘플 메일을 못 받았습니다.
![스크린샷 2021-07-20 오전 10 31 52](https://user-images.githubusercontent.com/46298150/126248669-4812308d-3fa4-4b35-9ef2-f50f51105298.png)

**Comment by Kyejeong** [comment]
> > > > > 촉구 캠페인의 샘플 메일이 7/13 이후 전달되지 않고 있어요. 어떤 상황인지 궁금해서 연락드려요. @dalikim
> > > > > ![스크린샷 2021-07-15 오후 8 13 42](https://user-images.githubusercontent.com/46298150/125779184-20f23087-0a03-4b1a-a684-6d7e715408c2.png)
> > > > 
> > > > 
> > > > 이런이런 ㅠㅠ 오늘 샘플 메일 발송이 되는지 확인해 주시겠어요?
> > > 
> > > 
> > > 수요일(7/14), 어제(7/15), 오늘(7/16) 받은 샘플 메일이 없습니다. @dalikim
> > 
> > 
> > 계속 발송되고 있고 최근에 2021-07-19 16:44:47 발송된 것으로 나옵니다. 샘플 메일은 계속 나가지 않고 있나요?
> > 7월 14일부터 샘플 메일을 못 받았습니다.
> > ![스크린샷 2021-07-20 오전 10 31 52](https://user-images.githubusercontent.com/46298150/126248669-4812308d-3fa4-4b35-9ef2-f50f51105298.png)
@dalikim

**Comment by dalikim** [comment]
혹시 스팸함에 있지는 않나요?
