### ISSUE TITLE
캠페인즈 푸터 > '문의' 클릭 시 연결되는 주소 변경

### ISSUE THREAD

**Issue by Doran-oh** [parti-coop/campaigns#295]
캠페인즈 푸터에서 '문의'를 클릭할 시 민활커의 '데이터활동가'채널로 연결됩니다. 
올바른 캠페인즈 Q&A 채널로 연결을 수정 부탁드립니다. 
연결할 주소: https://democracy-activists.parti.xyz/front/posts/41189 

감사합니다.

**Comment by dalikim** [comment]
@Doran-oh 흠 문의를 클릭해서 카누 가입까지 하고 하는 건 무리 같아요. 이메일 쓰기로 연결하면 합니다.

@Doran-oh @ramsci82 님을 contact@campaigns.kr 메일링으로 초대했서요.

**Comment by Doran-oh** [comment]
넵 확인했습니다.
