### ISSUE TITLE
캠페인 마감 날짜를 등록할 수 있으면 좋겠습니다.

### ISSUE THREAD

**Issue by Doran-oh** [parti-coop/campaigns#299]
마감일 등록할 수 있는지 문의가 있었습니다. 

마감일이 분명하게 예정되어 있는 경우에도 현재는 시스템상 마감일을 설정할 수 없습니다. 
마감일자와 마감시간을 등록할 수 있으면 수동으로 마감하지 않아도 될 것 같아서 좋을 것 같아요.

**Comment by Kyejeong** [comment]
> 마감일 등록할 수 있는지 문의가 있었습니다.
> 
> 마감일이 분명하게 예정되어 있는 경우에도 현재는 시스템상 마감일을 설정할 수 없습니다.
> 마감일자와 마감시간을 등록할 수 있으면 수동으로 마감하지 않아도 될 것 같아서 좋을 것 같아요.

반가운 제안이라 댓글 남깁니다. 캠페인의 마감일 등록은 평소에 있었으면 있으면 좋겠다고 생각한 기능입니다.

**Comment by Kyejeong** [comment]
> 

오랜만에 인사드려요. 혹시, 마감일 등록 기능이 추가될 수 있는지 궁금합니다.

**Comment by dongown** [comment]
이 이슈는 얼마 전, 기후환경유권자행동에서도 문의가 있었습니다. 
지금은 수동으로 종료를 누를 수밖에 없기에, 처음부터 마감일을 지정할 수 있도록 추가되면 좋겠다는 생각이 드네요.

**Comment by rest515** [comment]
네네. 이번 시즌에 가능하면 넣어 보죠.

**Comment by dongown** [comment]
@Kyejeong 드디어 마감일 등록 기능을 추가했습니다 :)
