### ISSUE TITLE
촉구하기 캠페인에서 샘플 메일을 받지 못했습니다. 이유가 무엇일까요?

### ISSUE THREAD

**Issue by Kyejeong** [parti-coop/campaigns#301]
안녕하세요. 참여연대에서 일하는 이계정입니다. 
저희가 지난 8월 4일 촉구하기 캠페인 [https://campaigns.kr/campaigns/425](url)을 오픈해서 현재 활동 중입니다. 
이 캠페인의 촉구하기 샘플 메일을 한 통도 받지 못했습니다. 이유가 궁금해서 여쭤봅니다. @dalikim

**Comment by rest515** [comment]
이 문제는 이제 해결된 것으로 보여서 이슈를 닫겠습니다.
