### ISSUE TITLE
팻말들기에서 맵핑이 되지 않아 개선이 필요합니다.

### ISSUE THREAD

**Issue by Mee-parti** [parti-coop/campaigns#304]
GPS를 켜고 사진을 올리지만, 
팻말로는 올라가지만 지도에 핀이 찍히지 않습니다.

춘천 다음주 오프라인행사를 하면서 캠페인즈 활용을 하실 수 있다고 소개드렸는데요. 해보려하니 안되어서 개선 요청을 드립니다.

혹시 시간이 소요되는 건이면 행사에서도 다른 결정을 해야하는 상황입니다. 편히 말씀해주세요.

**Comment by Mee-parti** [comment]
https://campaigns.kr/campaigns/523/pickets
지도위에 팻말이 찍히지 않아요.

**Comment by ssinkjung** [comment]
테스트해봤는데
저도 https://campaigns.kr/campaigns/523/pickets 이 춘천 캠페인은 맵핑이 안 되네요.

지도 모으기 캠페인 전체가 그런건가 해서 예전[ 일회용컵 모으기](https://campaigns.kr/campaigns/160/pickets) 캠페인 테스트 해봤는데, 이건 맵핑이 될 때도 있고, 안 될 때도 있군요. 예전에도 어떤 사진은 되고, 어떤 사진은 안 되더라구요. 

참고로 '주소' 칸에 주소를 입력하면 무조건 작동하긴 합니다.

@Mee-parti 님 혹시 모르니 캠페인을 다시 한번 만들어보시는 건 어떠세요.

**Comment by rest515** [comment]
이 이슈는 다음에 또 문제가 발생할떄 처리할께요.
