### ISSUE TITLE
캠페인에 서명한 내용을 삭제 또는 숨김 처리 기능이 필요합니다. 

### ISSUE THREAD

**Issue by breadnrose** [parti-coop/campaigns#308]
다른 캠페인들은 있는데, 서명하기 캠페인의 경우 이미 서명한 내용을 숨기거나 신고, 삭제 처리하는 기능이 없네요. 부적절한 메세지가 있을 경우를 대응방안이 필요해 보입니다.

**Comment by wagurano** [comment]
서명내용 아래에 '신고'(로그인 필요) 와 '삭제'(관리자/admin 권한 필요) 버튼을 달았습니다.
https://github.com/parti-coop/campaigns/commit/25082672776bc0d3e16683823165d77cd0e1c5de
