### ISSUE TITLE
[빠띠 캠페인즈] 글쓰기하다가 일정 시간이 지나면 오류 발생

### ISSUE THREAD

**Issue by Kyejeong** [parti-coop/campaigns#309]
안녕하세요. 참여연대에서 일하는 이계정입니다. 
빠띠 캠페인즈에서 글쓰기 상태에서 1분 이상 유지된 후 '서명하기' 버튼을 클릭하면 "reCAPTCHA 인증이 실패했습니다. 잠시 후 다시 시도해 주세요"라는 메시지가 뜨고 쓰던 글이 모두 사라지는 현상이 발생합니다. (첨부 파일 참조)

현재 진행하는 서명 캠페인 https://campaigns.kr/campaigns/587

오류를 수정할 방안이 있을까요?
![스크린샷 2022-02-28 오후 3 45 05](https://user-images.githubusercontent.com/46298150/155937331-88e5a719-4f7c-4f67-9bd5-8c2bed031b49.png) @dalikim

**Comment by rest515** [comment]
안녕하세요, "글쓰기 상태"라는게 어떤 상태를 가리키는 것일까요?

**Comment by Kyejeong** [comment]
> > 안녕하세요, "글쓰기 상태"라는게 어떤 상태를 가리키는 것일까요?
> > ![스크린샷 2022-03-02 오후 5 13 54](https://user-images.githubusercontent.com/46298150/156321781-33f67cd1-11b9-446d-81ba-bc813721e458.png)
> > 글쓰기 상태는 서명하기 버튼 클릭 후, 참여하는 과정을 얘기하는 것입니다. @rest515 @dalikim
안녕하세요. 혹시 오류 상황은 확인해보셨을까요? 참고로, 캠페인을 알리는 메시지를 이메일/카톡/문자로 내일(3/4) 오후 1시에 2만여 명에게 발송 예정입니다. @rest515 @dalikim

**Comment by dalikim** [comment]
처리되었습니다.

**Comment by Kyejeong** [comment]
처리된 메시지 잘 받았어요.
[서명한 뒤에 표시되는 문구(선택)] 칸에 예전 문구를 다시 넣고 테스트를 했더니, 서명 완료는 가능했지만 캡쳐 이미지가 뜨더라고요.
<img width="899" alt="스크린샷 2022-03-05 오후 6 48 09" src="https://user-images.githubusercontent.com/46298150/156878246-126c7271-44a9-44c7-8a44-537e222aba17.png">
현재, [서명한 뒤에 표시되는 문구(선택)] 문구는 다시 삭제했어요 @dalikim

**Comment by dalikim** [comment]
https://github.com/parti-coop/campaigns/issues/311 에서 처리 중입니다.

> 처리된 메시지 잘 받았어요.
> [서명한 뒤에 표시되는 문구(선택)] 칸에 예전 문구를 다시 넣고 테스트를 했더니, 서명 완료는 가능했지만 캡쳐 이미지가 뜨더라고요.
