### ISSUE TITLE
캠페인 서명 이후 표시될 문구가 꽤 길면 오류가 발생합니다.

### ISSUE THREAD

**Issue by dalikim** [parti-coop/campaigns#311]

**Comment by dalikim** [comment]
@Kyejeong 오류가 수정되었습니다.

**Comment by Kyejeong** [comment]
[서명한 뒤에 표시되는 문구] 추가하고나서 테스트해봤더니 오류가 발생하기 않았습니다. 오류 수정해주셔서 고맙습니다! 

오류 확인 과정에서 테스트한 글이 3개 있어요. 115번/116번/124번째 서명자 삭제 부탁드려요. @dalikim
![스크린샷 2022-03-10 오후 3 41 04](https://user-images.githubusercontent.com/46298150/157604655-3987a512-d248-4e34-923f-6ec8f74dab6a.png)
![스크린샷 2022-03-10 오후 3 39 37](https://user-images.githubusercontent.com/46298150/157604668-f6bc702a-9a98-48c6-9593-9dbb3ef41f4f.png)

**Comment by dalikim** [comment]
@Kyejeong 삭제하였습니다.

**Comment by Kyejeong** [comment]
> @Kyejeong 삭제하였습니다.

빠르게 해결해주셔서 고맙습니다!
