### ISSUE TITLE
GA 코드를 삽입합니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#314]
빠띠 캠페인즈 페이지뷰, 방문자 수 등을 추적하기 위해 GA 코드를 삽입해야 합니다.(이전의 코드는 삭제된 상황)

캠페인즈 html head 섹션에 다음 코드 삽입([관련 위키](https://neo.parti.xyz/front/posts/48456))

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-NFM8MCY19Y"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-NFM8MCY19Y');
</script>
```

**Comment by dalikim** [comment]
@jjuwoo 연주님 캠페인즈 GA개설한 사람이 조직에 개설하지 않았던 터라, 개인 계정 정리하면서 캠페인즈도 지워버리면서 몇 년치가 날라간 상황입니다. ㅠㅠ

혹시 이김에 GA가 아니라 GTM으로 세팅하고 GA4로 변경하면 어떨까 싶어요. 의견 주세요.

**Comment by jjuwoo** [comment]
넵 좋습니다. 제가 트리님과 같이 GTA 만들어서 코드 공유드릴께요
@dongown 트리님 같이 만들어볼까요~ 몸 괜찮아지시면 회의 잡아주세요.

**Comment by dongown** [comment]
@dalikim 코드 공유드립니다.

페이지의 <head>에서 가능한 한 높은 위치에 코드를 붙여넣으세요.
```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NPFTJLH');</script>
<!-- End Google Tag Manager -->
```

또한 여는 <body> 태그 바로 뒤에 코드를 붙여넣으세요.
```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NPFTJLH"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

**Comment by dalikim** [comment]
@dongown @jjuwoo @breadnrose 배포했습니다. 내일 늦게, 혹은 모레 아침에 구글 애널리틱스 수집 상황 확인해 보죠.

**Comment by jjuwoo** [comment]
> @dongown @jjuwoo @breadnrose 배포했습니다. 내일 늦게, 혹은 모레 아침에 구글 애널리틱스 수집 상황 확인해 보죠.

수집 확인했습니다. 아직 데이터가 많지 않으니 수요일쯤 한번 더 체크하겠습니다. 
![image](https://user-images.githubusercontent.com/10860472/160308435-8d3e363b-fa33-4be8-822c-f4d7747936a1.png)

**Comment by jjuwoo** [comment]
@wagurano 
body 넣어야 하는 태그 적용이 안된것 같습니다.
<img width="598" alt="image" src="https://user-images.githubusercontent.com/10860472/162934310-85d2677f-b9b2-4117-8128-1ce73185f7ac.png">

27,28일 데이터가 있는데 그 후로 수집된게 없네요.
<img width="699" alt="image" src="https://user-images.githubusercontent.com/10860472/162934114-ebf46b83-e7e3-4202-ba50-a31d0938bb3c.png">

**Comment by rest515** [comment]
소스에는 모두 제대로 들어간 것 같은데요. 다른 걸 챙길게 있을까요?

**Comment by jjuwoo** [comment]
> 소스에는 모두 제대로 들어간 것 같은데요. 다른 걸 챙길게 있을까요?

흠... GTM 설정확인하고 있는데 제가 관리자가 아니라서 제출버튼이 안보이는것 같습니다. 트리님께 권한 요청했으니 설정 살펴보겠습니다.

**Comment by jjuwoo** [comment]
수집처리 완료하고 수집되는것 확인했습니다. 
내일이랑 다음주 데이터 잘 수집되고있는지 살펴봐달리고 트리님께 요청드려놓았습니다.

**Comment by dongown** [comment]
데이터 이상없이 수집되고 있습니다 :)
