### ISSUE TITLE
인기 캠페인/메인 배너 노출

### ISSUE THREAD

**Issue by wagurano** [parti-coop/campaigns#320]

**Comment by dongown** [comment]
한살림 기후밥상챌린지를  2022년 11월 30일까지 인기 캠페인에 노출합니다.
링크 : https://campaigns.kr/campaigns/591/pickets

**Comment by breadnrose** [comment]
@rest515 한살림 캠페인은 참여자수가 높은데 인기 캠페인이나 메인에 노출이 안되네요. 지금 노출된 것이 다 서명캠페인인데, 팻말들기라서 안되는 것인가 싶기도. 
시스님, 한살림 캠페인 노출하는 거 바로 진행하실 수 있을까요? (한살림쪽에 대략 이번주까지도 말씀 드렸는데, 제가 못 챙겼네요.)

**Comment by rest515** [comment]
넵

**Comment by dongown** [comment]
@rest515 현재 인기 캠페인에 한살림 캠페인이 중복으로 노출됩니다. 임시로 탑에 보여준 것과 사람들이 많이 참여해 자동으로 노출된 것이 동시에 진행되지 않았나 싶네요. 한살림 캠페인 하나를 메인에서 내립니다. (자동 노출된 건을 내리면 어떨까 싶네요. 임시로 올라간 것을 메인에서 내리면 나중에 한살림 캠페인 참여가 저조해질 때 메인에서 아예 사라질 수도 있으니)

![스크린샷 2022-04-26 오전 2 11 47](https://user-images.githubusercontent.com/72062336/165139327-8116875d-2740-46b1-a097-cd17c53ab2ac.png)

**Comment by dongown** [comment]
한살림 기후밥상챌린지를 2022년 11월 30일까지 인기 캠페인에 노출합니다.
링크 : https://campaigns.kr/campaigns/591

중복으로 노출이 되는 경우에는 어떻게 해결하면 좋을까요? 저희가 강제로 노출시킨 것과, 자동으로 노출이 되는 경우 2개 다 노출이 되는 상황이 이전에 발생했습니다.

**Comment by dongown** [comment]
한번 더 확인부탁드려요. 아직 인기 캠페인에 노출되지 않고 있습니다.
(https://campaigns.kr/campaigns/591)
![스크린샷 2022-05-19 오후 11 57 57](https://user-images.githubusercontent.com/72062336/169327284-1aef202c-bbd3-4e7f-8f7a-72d09fcc193a.png)

**Comment by rest515** [comment]
특집 캠페인을 운영자가 지정할 수 있는 기능을 추가할께요.

**Comment by dongown** [comment]
네네 알겠습니다. 시즌 3 일감으로 생각하면 될까요!?

**Comment by dongown** [comment]
이상없이 작동합니다 :) 추가로 여쭤볼 것이 있는데요, 지금 특집 캠페인에 노출되는 캠페인은 3개(1줄)일까요?
1줄 이상은 의도적으로라도 만들지 않을 것 같지만 한번 확인차 여쭤봅니다.
