### ISSUE TITLE
서명하기 성공시 진행상태를 두줄에서 한줄로 표시하기

### ISSUE THREAD

**Issue by wagurano** [parti-coop/campaigns#324]
![image](https://user-images.githubusercontent.com/2429132/161753420-777ab6e5-3606-40a7-a068-83a6cf87b584.png)
서명하기 캠페인에서 100% 이상 성공 달성한 경우, 진행상태 표시 바를 두줄로 보여주는데, 한줄로 보여주세요.
https://campaigns.kr/campaigns/570/signers

**Comment by rest515** [comment]
전반적으로 부트스트랩이 꼬인 느낌인데요. 우선 급히 패치하고 나중에 CSS 프레임워크를 고칠때 더 손을 보겠습니다.
