### ISSUE TITLE
다운로드시에 태그 값도 포함합니다

### ISSUE THREAD

**Issue by rest515** [parti-coop/campaigns#329]

**Comment by breadnrose** [comment]
@rest515 시스님 이것도 한살림 쪽에서 요청 주신 내용이라 이번주, 안되면 4/20 정도까지 진행되면 좋을 것 같습니다.

**Comment by dongown** [comment]
데이터를 다운로드 했을 시 태그 항목에 
한글 태그가 아닌, #<ActsAsTaggableOn::Tag::ActiveRecord_Associations_CollectionProxy:0x00007f967d337a00> 라고 나옵니다.

[한살림 데이터] - https://campaigns.kr/campaigns/591
<img width="1438" alt="스크린샷 2022-04-18 오전 10 47 43" src="https://user-images.githubusercontent.com/72062336/163741915-369c2aa0-b5ab-4fda-8631-31edac388a8d.png">

또한 어떤 캠페인은 태그 데이터가 포함되지 않습니다.
[사이버렉카 데이터] - https://campaigns.kr/campaigns/585 
<img width="1439" alt="스크린샷 2022-04-18 오전 10 49 03" src="https://user-images.githubusercontent.com/72062336/163742019-5653d000-61cb-4574-afe5-e367a6a5450d.png">

**Comment by rest515** [comment]
사이버렉카는 개인정보동의가 되어 있을까요?

**Comment by dongown** [comment]
아, 사이버렉카는 개인정보동의가 되어 있지 않아요. 그럴 경우에는 태그 데이터는 포함되지 않는거군요.

**Comment by dongown** [comment]
@breadnrose 한살림에 이제 태그 데이터도 다운받아진다고 연락하면 될 것 같습니다.

**Comment by rest515** [comment]
어떻게 처리하는게 좋을지 결정하면 될 것 같습니다. 태그는 민감한 개인정보로 분류하지 않는게 맞을까요? 사실 어떻게 쓰이냐에 따라 달라질 수 있어서 좀 애매하긴 합니다.
