### ISSUE TITLE
소식 개선 - 메일 발송 양식(에디터)을 개선합니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#335]
단체에서 소식으로 이메일 발송을 적극적으로 하기 위해서는, 소식에 작성했던 에디팅에 맞추어 메일이 발송되어야 합니다.
지금 네이버는 줄간격이 없는 상황으로 메일이 발송되고 있습니다.

소식 원본 : https://campaigns.kr/campaigns/593/stories/430 
이메일 발송 : 상 - 지메일(올바른 방식) / 하 - 네이버(줄간격 오류)
![스크린샷 2022-04-13 오후 4 43 55](https://user-images.githubusercontent.com/72062336/163125792-b2e99aab-06e7-41ac-aa1a-3083b3ff1340.png)
![스크린샷 2022-04-13 오후 4 44 29](https://user-images.githubusercontent.com/72062336/163125889-e24da466-007a-4316-b3fd-ef549b2ab80e.png)

**Comment by rest515** [comment]
이 이슈는 좀 더 개발팀이 갖춰지면 진행하시죠.

**Comment by dongown** [comment]
네네 좋습니다. 에디터에 관한 문의는 종종 있지만 급한 기능은 아니니까요. 일단 시즌2에서 제외해놓을게요.

**Comment by rest515** [comment]
이게 지금 어떤 상태인지 확인해 주실 수 있을까요? @dongown

**Comment by dongown** [comment]
현재도 소식의 에디터가 '네이버 메일'에는 작동하지 않습니다.
예 - https://campaigns.kr/campaigns/654/stories/465

[상 - 네이버 메일로 발송되는 소식 / 하 - 소식 탭에 업로드한 글)
![네이버 메일](https://user-images.githubusercontent.com/72062336/180679926-b036a19a-f467-4e01-8299-a8d5c99d8f63.png)
-
![캠페인즈 소식 글](https://user-images.githubusercontent.com/72062336/180679973-81905774-935a-4f67-bd36-43475d09e18e.png)

**Comment by dongown** [comment]
에디터 개선이 우선순위일지는 잘 모르긴 하네요.

오히려 우선순위를 둔다면 빠띠 캠페인즈 가입자 이외에도 '캠페인에 이메일을 입력한 시민'에게도 이메일이 발송되도록 하면 어떨까? 싶긴 합니다.

소식 관련해서 시민들이 이메일을 받지 못했다는 문의가 종종 오는데요, 그때마다 '빠띠 캠페인즈에 가입한 사람'에게만 발송된다고 하면 살짝 실망(?)한 느낌을 받긴 합니다. 보통 서명하기, 촉구하기를 할 때 이메일도 함께 받는 경우가 있으니 '참여할 때 이메일을 입력한 사람'에게도 소식이 발송된다면 더 활발히 활용되고, 소식을 많이 볼 수 있지 않을까 싶어요.

**Comment by dongown** [comment]
@rest515 테스트 결과 참여할 때 이메일을 적은 사람에게 소식이 발송되는 것을 확인했습니다. 제가 잘못 알고 있었네요😅 죄송해요.
이전에 종종 소식을 발송했는데 못 받았다는 연락이 왔었는데, 다른 이유가 있었나 봅니다. 동일한 이슈가 발생하면 챙겨볼게요.

그 외 소식 개선사항 중

이메일 링크를 '캠페인'이 아니라 '소식'으로 연결하는 건을 진행해보면 어떨까요?
현재 에디터가 깨지는 등의 문제가 있기에,  캠페인즈에 올린 소식으로 접속해서 보면 좋겠다 싶습니다.
텍스트도 서명 진행상황에서 다음과 같이 변경하구요. 현재는 촉구, 서명, 목소리 등도 모두 '서명 진행상황 확인하기'라고 나옵니다.
서명 진행상황 확인하기 --> 소식 자세히보기

**Comment by rest515** [comment]
네. 그 정도 개선으로 마무리해보죠.

**Comment by dongown** [comment]
확인했습니다 :) 이상없이 잘 작동합니다!
