### ISSUE TITLE
소식 개선 - 팻말들기 소식 페이지에서 소식만 볼 수 있도록 합니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#336]
팻말들기에서 소식을 눌렀을 때 캠페인 내용과 함께 보여 소식을 확인하기 어렵습니다.
소식을 눌렀을 때 소식만 볼 수 있도록 합니다.

팻말들기 소식 페이지(스크롤을 한참 내려야 소식을 확인할 수 있음) : https://campaigns.kr/campaigns/591/stories 

제안 1. 소식에서 내용이 보이지 않도록 합니다.
제안 2. 팻말들기도 서명하기처럼 내용/팻말/소식 으로 구성을 변경합니다.

서명하기 : '내용/서명/소식'으로 구성되어 있고, 소식만 확인할 수 있음 (https://campaigns.kr/campaigns/593/stories) 
팻말들기 : '팻말'소식'으로 구성되어 있음

**Comment by rest515** [comment]
저도 이게 고민인데요.. 서명하기 처럼 구성을 바꾸는게 더 낫겠죠?

**Comment by dongown** [comment]
네네. 제안2에 적은 방향처럼 그게 나을 것 같아요.
