### ISSUE TITLE
캠페인즈 상단을 수정합니다.

### ISSUE THREAD

**Issue by breadnrose** [parti-coop/campaigns#340]
빠띠 캠페인즈 상단에 빠띠 캠페인즈를 로고를 넣고 옆에
- 빠띠 캠페인즈란?(https://democracy-activists.parti.xyz/front/posts/41175 : 이후에 홈페이지 구성이 될 경우 링크 교체) 
- 캠페인 시작하기(https://campaigns.kr/campaigns/new) 
텍스트 2개를 넣고 링크를 연결합니다.

**Comment by dongown** [comment]
캠페인즈 상단을 수정합니다.

(왼쪽 상단) ‘빠띠 캠페인즈 - 빠띠 캠페인즈란? (https://democracy-activists.parti.xyz/front/posts/41175)  - 캠페인 시작하기 ( https://campaigns.kr/campaigns/new)’ 를 배치합니다.
(오른쪽 상단)’검색 - 로그인 (https://campaigns.kr/users/sign_in)’ 을 배치합니다.

상단에 버튼이 많아지기에 [모바일]에는 적합하지 않아 모바일은 현재와 같이 유지합니다.
대신 햄버거 메뉴를 수정합니다.(따로 이슈 등록 예정)

**Comment by dongown** [comment]
참고 : 빠띠 믹스 (https://parti.mx/)
<img width="1418" alt="스크린샷 2022-04-23 오전 12 41 35" src="https://user-images.githubusercontent.com/72062336/164748440-48e9e967-8cbc-4826-ac23-66da8faad07e.png">

체인지닷오알지 (https://www.change.org/)
<img width="1022" alt="스크린샷 2022-04-23 오전 12 42 13" src="https://user-images.githubusercontent.com/72062336/164748542-85159ab6-2e3e-49b7-9b83-ea3f81808e82.png">
