### ISSUE TITLE
캠페인즈 어드민에 캠페인 참여자 수 데이터를 추가합니다.

### ISSUE THREAD

**Issue by breadnrose** [parti-coop/campaigns#341]
개설된 캠페인의 전체 참여자 수를 어드민에서 확인할 수 있도록 합니다.

**Comment by rest515** [comment]
![image](https://user-images.githubusercontent.com/794973/163655379-91baef0f-bdf5-43c1-b828-46e1df166469.png)

운영툴에 간단히 추가하겠습니다.

**Comment by dongown** [comment]
촉구 전체는 '촉구 캠페인'에 참여한 사람들의 수가 맞을까요? 다른 데이터와 차이가 많이 나서 한번 여쭤봅니다.

**Comment by dongown** [comment]
@rest515 혹시 어드민 통계치가 어떻게 계산되는지 여쭤봐도 될까요?
지표를 작성하던 중, 촉구 전체의 수가 줄어들어서 한번 체크해보고자 합니다.

[4/25 기준]
서명 전체 296,786
팻말, 추모 전체 84,058
촉구 전체 6,503,988

[5/9 기준]
서명 전체 298,433
팻말, 추모 전체 84,355
촉구 전체 6,503,928

**Comment by rest515** [comment]
촉구에 참여한 사람의 숫자는 아니고.. 촉구를 한 숫자인데요. 한 사람이 여러 명에게 촉구를 할 수 있으니까 꽤 숫자가 커집니다.

줄어든 이유는 이상하네요. 혹시 이미 진행한 캠페인을 삭제한 경우가 아닐까 싶은데.. 혹시 @dalikim 님 확인 부탁드릴 수 있을까요?

**Comment by dalikim** [comment]
글쎄요. 댓글이나 촉구 대상이 삭제되면 촉구가 지워지기는 합니다.

**Comment by dongown** [comment]
네네 알겠습니다 :) 지금 당장은 알 수는 없겠군요. 다음에 이런 일이 발생하면 한번 주요 캠페인 위주로 대상이 삭제되었는지를 확인해볼게요.
