### ISSUE TITLE
커버이미지 파일 등록시 사이즈 크기를 안내문구를 삽입합니다. 

### ISSUE THREAD

**Issue by breadnrose** [parti-coop/campaigns#343]
현재) 커버이미지(선택)
수정안) 커버이미지(선택) - 권장 사이즈 가로 1440*810(px)

**Comment by dongown** [comment]
사소할 수도 있겠지만 지금 이야기하지 않으면 영원히 지나갈 듯 해서 남겨봅니다.
'가로'라는 글씨가 들어갈 필요가 있을까요? 권장 사이즈 1440*810(px) 라고 해도 가로*세로라는 의미가 전달되지 않을까 싶습니다.
