### ISSUE TITLE
소셜 공유 이미지 등록시 커버이미지가 보입니다.

### ISSUE THREAD

**Issue by breadnrose** [parti-coop/campaigns#344]
- 커버이미지와 다른 파일로(다른 이미지로) 소셜 공유 이미지를 등록했으나 링크를 공유하면 커버이미지로 보입니다. 
- 소셜공유이미지 권장 사이즈 안내 문구를 삽입하면 좋겠습니다. 권장 사이즈 1200x630(px)

**Comment by rest515** [comment]
제가 로컬에서 테스트해보니 소셜공유이미지가 잘 반영되는데요. 어디서 문제가 발생한 것일까요?

**Comment by dongown** [comment]
저도 테스트해보니 잘 반영됩니다. @breadnrose 혹시 한번 더 확인부탁드려도 될까요?

**Comment by dongown** [comment]
저도 테스트해보니 잘 반영됩니다. @breadnrose 혹시 한번 더 확인부탁드려도 될까요?

**Comment by breadnrose** [comment]
네. 지금은 잘 되네요.

**Comment by dongown** [comment]
네네 알겠습니다 :) 이슈 닫겠습니다!
