### ISSUE TITLE
팻말들기 패널 디자인을 좀 더 인스타그램스럽게 바꿔 봅니다

### ISSUE THREAD

**Issue by rest515** [parti-coop/campaigns#345]

**Comment by breadnrose** [comment]
팻말 리스트가 길어지는 경우 "참여하기"가 사라지는데 계속 보이면 좋을 것 같습니다. 

<img width="320" alt="1" src="https://user-images.githubusercontent.com/81340305/163509131-40893f7e-8de9-46a9-a13b-674c71a8eaaf.png">
<img width="320" alt="2" src="https://user-images.githubusercontent.com/81340305/163509137-69d4b2ae-29db-401f-9b6f-723a6a014c82.png">

**Comment by dongown** [comment]
참여하기가 사라질 때 스크롤을 최상단으로 올리거나, 최하단으로 내렸을 때 다시 나타납니다.

이게 이번 배포 때문에 이런 것인지, 원래 이랬던 것인지 명확하게는 모르겠네요.
