### ISSUE TITLE
팻말들기 AS - 태그 목록을 살립니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#348]
현재 팻말들기에서 태그 목록이 화면에서 사라졌습니다.
태그 목록을 이전처럼 되살립니다.

[현재 팻말들기 화면 - 태그가 없음]

**Comment by rest515** [comment]
네네. 설명과 같이 두기엔 너무 좁아서. 팻말 탭에만 태그를 넣었습니다.

**Comment by dongown** [comment]
@rest515 말씀해주신 것처럼 내용 페이지에는 태그가 없어도 될 것 같아요. 배포 완료로 처리하겠습니다.

**Comment by rest515** [comment]
네네 그리고 인증샷이긴 하지만.. 개인정보이기도 하니까, 스크린샷은 지우면 어떨까요?

**Comment by dongown** [comment]
스크린샷 삭제했습니다 :)
