### ISSUE TITLE
지도에 모으기 AS - 지도를 다시 살립니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#349]
현재 지도에 모으기에 지도가 사라진 상황입니다.
다시 이전처럼 지도를 살립니다.

지도에 모으기 링크 : https://campaigns.kr/campaigns/160, https://wouldyouparty.campaigns.kr/campaigns/136

[현재 지도에 모으기 화면]
![스크린샷 2022-04-16 오전 12 20 38](https://user-images.githubusercontent.com/72062336/163588803-2b220f4b-1d85-4c02-a2f7-91948b1bf21a.png)

[이전 지도에 모으기 화면]
<img width="363" alt="스크린샷 2022-04-16 오전 12 20 48" src="https://user-images.githubusercontent.com/72062336/163588814-f2ca3760-7d46-4516-8c52-406d17560f51.png">

**Comment by rest515** [comment]
![image](https://user-images.githubusercontent.com/794973/163654168-8c43fe19-57bd-4ad0-b847-da6f44a053b2.png)

탭 이름을 지도로 바꾸어서 넣어봤습니다. 내용 페이지에 넣으려니 너무 길어지는 느낌이 있네요.

**Comment by rest515** [comment]
내용 탭에 작은 지도로 추가하였습니다.

![image](https://user-images.githubusercontent.com/794973/163654858-853fdbaf-89af-47b3-9054-e3c1958ce3b4.png)
