### ISSUE TITLE
유저 페이지 - 아이디가 URL로 설정되도록 합니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#356]
아이디가 URL로 설정되도록 합니다. 또는 유저가 유저 페이지 URL을 설정할 수 있도록 합니다.

현재 : https://campaigns.kr/users/188 
제안 : https://campaigns.kr/user/peoplepower21 또는 https://campaigns.kr/peoplepower21

**Comment by dongown** [comment]
아이디와 URL 설정을 따로 할지, 아이디를 URL로 되도록 설정할지 고민이네요.
기존에 가입된 가입자의 수를 생각하면 아이디가 URL로 되도록 하는 편이 편하겠다는 생각이 들긴 합니다.

**Comment by rest515** [comment]
첫번째 제안 방식으로 작업했습니다. 그리고 프로필 수정 페이지에서 "주소로 쓸 아이디"에 지정하면 됩니다. 캠페이너들에게 가이드를 보내드려도 좋겠네요.

**Comment by dongown** [comment]
네네 가입자에게 프로필 관련 사항 메일을 발송해야겠네요.

프로필 수정 페이지에서 URL 설정은 확인했는데, 가입할 때는 URL을 물어보지 않아도 될까? 싶은 생각이 들긴 하네요.

가입에서 프로필 사진, 설명, URL 까지 한번에 한다면 프로필을 설정한 상태로 만들어지겠지만 그만큼 가입의 장벽이 높아져서 걱정이네요.
혹은 가입 이후에 모달 형식으로 프로필을 설정해달라는 것을 띄우는 방법도 나중에는 좋겠다는 생각이 듭니다.

<img width="301" alt="스크린샷 2022-05-15 오후 2 51 51" src="https://user-images.githubusercontent.com/72062336/168459139-ee2d56bf-c00d-4fb9-97c7-85bc92e72adf.png">

**Comment by rest515** [comment]
네네. 대부분의 사용자는 캠페인을 만들기보단, 캠페인에 참여하기 위해서 가입하는 것이어서.. 캠페인을 개설한 사용자에게 요청하는게 어떨까 싶습니다.

**Comment by dongown** [comment]
네 좋습니다 :) 이 이슈도 배포 완료로 마무리하겠습니다!

**Comment by dongown** [comment]
이번에 프로필 화면도 바뀌고, 캠페인에도 프로필이 노출되다보니 아직 따로 안내를 하지 않았음에도 불구하고, 아이디변경을 하는 분들이 많이 보이네요 :)
