### ISSUE TITLE
캠페인 분류를 관리합니다

### ISSUE THREAD

**Issue by rest515** [parti-coop/campaigns#359]
특히 기후환경 캠페인을 모아 보여줍니다.

**Comment by rest515** [comment]
이슈로 연결합니다.

**Comment by dongown** [comment]
혹시 이 부분은 어떤 내용일까요? 팀에서 챙기거나 의견을 주어야 하는 부분이 있을까요?

**Comment by rest515** [comment]
캠페인도 이슈를 지정할 수 있게 할까 싶은데요. 어떨까요?

**Comment by dongown** [comment]
좋습니다 :) 이후에 활용할 수 있도록 쌓아놓으면 좋겠네요.

그런데 최근 워크샵에서 캠페인즈에 캠페인을 개설할 때 이슈 선택을 어려워하시는 분들이 많았어요.
환경 관련된 캠페인 워크샵이었는데, 환경 토픽에 이슈가 많은데도 불구하고 고민하시더라구요.
우선은 적용하되, 캠페인 개설하시는 분들의 이야기를 들어보면서 어떻게 하면 좋을지 생각해볼게요.
