### ISSUE TITLE
캠페인 상세설정이 잘 노출되도록 합니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#360]
단체에서 캠페인을 만들 때 상세설정을 놓쳐 이메일을 받지 못하거나, 개인정보 제 3자 제공 동의를 놓치는 경우가 있네요.
이 부분을 해결할 방법을 고민해보아야 할 듯 합니다.

예를 들면, 캠페인을 만든 뒤 설명과 함께 모달창을 띄운다거나.

**Comment by rest515** [comment]
좋습니다. 어떻게 하면 좋을까요?

**Comment by dongown** [comment]
떠오르는 방법을 적어봅니다. 유저를 귀찮게하고, 번거롭게 만드는 것은 아닐지 살짝 걱정이 들기도 하는데요, 괜찮겠죠?
1,2번은 상세설정에 무엇이 있는지와, 3명 이상을 모으면 메인에 노출된다는 내용을 담으면 될 것 같구요.
3번은 아예 별도의 페이지를 기획하는 방향이라 가능할지는 모르겠네요(혹은 v2.15로 진행해도 좋습니다)

1. 캠페인 개설된 이후에 안내 모달창 띄우기
2. 캠페인 항목 탭과 내용 사이에 유저만 확인할 수 있는 설명 추가하기
<img width="815" alt="텍스트 추가 위치" src="https://user-images.githubusercontent.com/72062336/177292004-a24e6ff1-99f9-4626-915e-92e2b1bee71e.png">
3. 캠페인 개설 이후에 행동을 안내하는 체크리스트 페이지로 이동하기 : 캠페인을 개설한 이후 캠페인 체크리스트를 보여주는 화면으로 이동하도록 합니다. 화면은 다음과 같습니다. 이를 통해 더 고민할 수 있도록 해서 캠페인 콘텐츠의 질을 높입니다. 체인지닷오알지에서는 캠페인 개설 이후에 캠페인을 공유하라는 안내 페이지로 이동하게 됩니다.

- 3명 이상을 모을 경우 캠페인즈에 노출됨(공유 링크)
- 캠페인 내용을 구성할 때 확인해야 하는 사항 체크리스트(예 - 구체적인 행동을 제안했나요?)
- 캠페인 자체에서 확인해야 하는 사항 체크리스트(예 - 참여자의 어떤 정보가 필요한가요?)

[참고 레퍼런스 - 체인지닷 오알지]
(좌 - 캠페인 개설 이후 나타나는 공유 제안 화면 / 우 - 캠페인 관리 페이지의 캠페인 체크리스트 화면)
<img width="300" alt="체인지닷오알지 캠페인 공유 제안 화면" src="https://user-images.githubusercontent.com/72062336/177292965-2493bbf3-4a8d-487b-b16f-3329a8761210.png"> <img width="350" alt="체인지닷오알지 캠페인 체크리스트 화면" src="https://user-images.githubusercontent.com/72062336/177293038-2242fb5a-1c68-4a1e-b760-028546ade668.png">

**Comment by rest515** [comment]
요 작업은 어떻게 정리가 될까요?

**Comment by dongown** [comment]
3가지 안 중에서 하나를 선택해보면 될 것 같습니다. 혹시 어떤 방향이 괜찮을까요? @ramsci82 님도 의견주셔도 좋습니다.

**Comment by rest515** [comment]
저는 3번째가 나을 것 같으네요.

**Comment by dongown** [comment]
이 이슈는 [#402 [캠페인 체크리스트] 캠페인 오른쪽 사이드바에 캠페인 체크리스트를 추가합니다.](https://github.com/parti-coop/campaigns/issues/402) 에서 논의를 이어서 진행합니다.
