### ISSUE TITLE
메인 페이지 AS - 캠페인즈 상단 배너에 캠페인을 노출합니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#362]
원래 상단 배너에 인기 캠페인이 랜덤으로 노출되었었는데요,
이번 배포 이후에 사라졌네요.

혹시 일부러 없애신 것일까요? 

<img width="1420" alt="스크린샷 2022-05-12 오전 2 15 28" src="https://user-images.githubusercontent.com/72062336/167908481-3809a383-ed32-4e11-a0fb-bf096985794b.png">

**Comment by rest515** [comment]
다시 추가하였습니다.
