### ISSUE TITLE
[지방선거 페이지 AS] 배너 링크를 버튼으로 한정합니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#367]
지방선거 페이지 배너 전체에 링크(https://campaigns.kr/campaigns/new)가 연결되어 있습니다.
배너에서 새 캠페인 만들기 버튼에만 링크(https://campaigns.kr/campaigns/new)를 연결합니다.

<img width="1436" alt="스크린샷 2022-05-19 오후 4 00 33" src="https://user-images.githubusercontent.com/72062336/169230362-83abeb63-6e22-40f4-9f1b-1c89389fbb32.png">

**Comment by dongown** [comment]
@rest515 추가로 배너 버튼 관련 생각 남겨요.

배너의 버튼을 **'캠페인 만들기' '응답 확인하기'** 이렇게 두개로 해볼까? 하는 생각도 드네요.
캠페인 수도 생각보다 많아지고, 소식도 길다보니 의외로 답변이 잘 노출되지 않는 것 같아서요.
현재 배너의 문구에서 '후보자의 응답을 확인해요'가 있으니 바로 응답을 확인할 수 있도록 클릭하면 연결되도록 하면 어떨까 싶습니다.

**Comment by rest515** [comment]
아 근데 버튼 구분하려면 디자인도 바꿔야 하고 개발할게 많습니다.

**Comment by dongown** [comment]
아 그렇군요. 그러면 버튼은 지금처럼 하나로 진행하면 되겠습니다. 그렇다면 링크를 버튼으로만 한정하는 것은 가능할까요?

**Comment by rest515** [comment]
가능한데 저나 무명님 작업이 필요합니다. 굳이 해야 하나 싶으네요.

**Comment by dongown** [comment]
네네 알겠습니다 :) 이슈는 닫아놓을게요!
