### ISSUE TITLE
[촉구하기 기능요청] 이름을 적는 공간에 추가 설명을 작성합니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#371]
[2022 지방선거 기후 유권자 행동 요청사항]
"빠띠 촉구하기에 촉구시민의 이름 또는 별칭으로 표기 가능한가요? 실명을 적는 것이 부담스럽다는 사람들이 있어 요청합니다."

현재 촉구하기를 누를 경우 '이름'과 '이메일'을 적도록 되어 있습니다.
'이름 -> 이름(혹은 별명)' 으로 텍스트를 수정합니다.

<img width="1047" alt="스크린샷 2022-05-23 오후 7 03 32" src="https://user-images.githubusercontent.com/72062336/169795703-06488e21-c007-4661-907a-5c4ae5cdf06a.png">

**Comment by dongown** [comment]
@rest515 촉구하기 관련 요청사항이 있습니다. 직접 이름을 입력하기 부담스러워 참여하지 못했다는 사람이 있다고 해요. 촉구하기는 내 이름과 내 이메일로 직접 한다는 점에서 효능감이 있다고 보긴 하는데요, 이 기능을 어떻게 하면 좋을까요?

**Comment by rest515** [comment]
일방적으로 스팸을 보내는게 목표가 아니기 때문에, 이름과 이메일을 요구하는 건데요. 좀 어렵더라도 지금 정책은 최소한 유지하는게 맞을 것 같습니다.

**Comment by dongown** [comment]
네네. 장벽이 조금 있는 편이 촉구하기에는 더 어울리겠다는 생각이 드네요. 그리고 당연한 것이기도 하겠구요.
단체에도 내일 한번 설명을 잘 해보도록 하겠습니다.

**Comment by rest515** [comment]
네네, 우리가 촉구 대상자를 단순히 폭탄 메일을 보내서 괴롭히려고 하는게 아니라, 의견을 전달하려는  거니까요.
