### ISSUE TITLE
촉구 대상자에게 메일을 보낼때 캠페이너의 메일 주소를 참조로 넣습니다

### ISSUE THREAD

**Issue by rest515** [parti-coop/campaigns#373]
답변 역시 참조로 넣은 담당자에게 가도록 조치합니다.

**Comment by dongown** [comment]
이 이슈도 v2.14에서 처리할 예정이신가요? 간단하게라도 추가 기획이 필요하다면 말씀해주세요 :)

**Comment by dongown** [comment]
@rest515 이 부분 내일 오전까지 작업해놓도록 하겠습니다. 혹시 시간 괜찮을까요?

**Comment by rest515** [comment]
넵

**Comment by dongown** [comment]
현재는 다음과 같이 촉구하기 메일이 발송됩니다.

보낸 사람 : contact@campaigns.kr

촉구 대상에게 발송되는 메일
-
(촉구 대상)님 안녕하세요? 세상을 바꾸는 시민들, 빠띠 캠페인즈입니다.
캠페인 (캠페인 명) (캠페인 URL) 이 진행 중입니다.
최근 ()명의 시민이 추가로 촉구하였습니다. 현재까지 총 ()명의 시민이 (촉구대상)님에게 촉구하였습니다.

캠페인 제목
캠페인 내용
자세히 보기(캠페인 링크)

다음과 같은 2가지를 추가하면 어떨까 싶습니다.
1. 보낸 사람에 참조로 캠페이너의 메일 주소 추가
2. 메일 내용에 캠페이너에게 문의하라는 텍스트 추가
: (캠페인 명)에 관해서 문의할 내용이 있다면 (캠페이너 아이디 - 링크 : 캠페이너 이메일)로 연락주세요.

[메일 구성안]
![예시 화면](https://user-images.githubusercontent.com/72062336/178555850-d68f711d-016d-413a-b7d8-6e988a2249ee.png)

**Comment by dongown** [comment]
이 부분은 촉구하기 메일 발송으로 테스트를 해보아야 해서, 시간이 조금 걸리겠네요😅
금요일까지 테스트 완료해놓도록 하겠습니다.

**Comment by rest515** [comment]
확인 부탁드려요 @dongown

**Comment by dongown** [comment]
@rest515 *이미지에는 개인의 이름이 노출되기에 깃헙 슬랙으로 공유드릴게요

현재 캠페이너에게 다음과 같이 이메일이 발송됩니다.
글씨 뒤의 URL은 삭제해도 되지 않을까 싶네요.

["성북구에서 버려지는 종이팩을 자원으로 되살려 쓰기 위한 책임 있는 조례 제정을 촉구합니다."](http://campaigns.kr/campaigns/687) http://campaigns.kr/campaigns/687
-> ["성북구에서 버려지는 종이팩을 자원으로 되살려 쓰기 위한 책임 있는 조례 제정을 촉구합니다."](http://campaigns.kr/campaigns/687)

[이미지 01]

그리고 캠페이너에 대한 설명이 메일 최하단에 위치해 있는데요, 촉구하기에 참여한 사람들의 수가 많을 경우 잘 노출되지 않을 것 같습니다. 이 내용을 상단으로 옮기면 어떨까요?

[이미지 02]

**Comment by rest515** [comment]
수정했습니다.

**Comment by dongown** [comment]
@rest515 테스트까지 완료했고, 이상 없습니다.

테스트하면서 깨달은 부분이 하나 있는데요, 캠페이너의 이메일을 참조로 넣다보니 촉구 메일이 발송될 때마다 계속 메일이 발송되고 있습니다.
현재는 촉구 메일을 발송할 때 캠페이너에게도 메일이 발송되는 것이 기능으로 있습니다.(샘플 메일을 발송합니다)

그렇다면 이제는 이 기능을 숨겨놓고, 촉구하기 기능을 설명할 때 촉구 이메일이 발송될 때마다 가입해주신 이메일로 메일이 발송된다는 사실을 안내하는 방식으로 진행하면 될까요?

<img width="1000" alt="샘플 메일 발송 이미지" src="https://user-images.githubusercontent.com/72062336/181691993-3113c99d-e39b-4c18-a308-67c87282d993.png">

**Comment by rest515** [comment]
넵. 샘플 메일 기능을 삭제했습니다.
