### ISSUE TITLE
[프로필 AS] 모바일 화면에서 프로필 설명이 잘 보이도록 합니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#377]
모바일 화면에서 프로필 간략소개, SNS 링크가 잘립니다.
모바일 화면에서도 프로필이 잘 나타나도록 합니다.

프로필 설명, 버튼이 잘린 프로필 페이지입니다.
링크 : https://campaigns.kr/users/youth4climateaction
<img width="302" alt="스크린샷 2022-06-03 오후 1 08 45" src="https://user-images.githubusercontent.com/72062336/171784273-49fec0ac-5c16-4063-9676-e333f22b9630.png">

글씨가 잘리지 않고 잘 보이는 프로필 페이지입니다.
링크 : https://campaigns.kr/users/moredazz
<img width="303" alt="스크린샷 2022-06-03 오후 1 10 28" src="https://user-images.githubusercontent.com/72062336/171784484-176e0a70-7e4e-4a77-bf64-d64c5adc61a5.png">

**Comment by rest515** [comment]
이메일 주소가 크게 나와서 그런건데.. 우선 이미지 폭을 조금 줄여볼께요.

**Comment by dongown** [comment]
이제 잘림 없이 모바일에서도 프로필이 잘 나타납니다 :)
