### ISSUE TITLE
[유저 페이지] 참여 캠페인을 노출합니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#379]
유저 페이지 캠페인 하단에 참여 캠페인을 노출합니다. 최근 참여한 캠페인 6개(2줄)를 노출하고, 그 이상은 '더보기'처리를 합니다.
노출된 캠페인은 나 자신만 확인할 수 있습니다.

[텍스트]
참여 캠페인

[현재 유저 페이지]
<img width="610" alt="현재 유저 페이지" src="https://user-images.githubusercontent.com/72062336/175845684-233669d7-54e9-45b1-8424-635bd4598eca.png">

**Comment by dongown** [comment]
1. 참여 캠페인 '더 보기' 유무 : 유저 페이지 스크롤이 길어진다는 생각에 참여 캠페인 노출을 6개(2줄)로 생각했는데요, 만약 나만 참여 캠페인을 볼 수 있다면 '더보기' 처리 없이 진행해도 되지 않을까 싶습니다. 
2. 참여 캠페인에 '나만 확인할 수 있다'는 표시 추가 : 유저의 입장에서는 참여 캠페인이 나만 확인할 수 있다는 사실을 모를 것 같습니다. 참여 캠페인 텍스트 옆에 작게 '나에게만 보입니다', 혹은 '나만 볼 수 있습니다'를 적어놓으면 어떨까요?

**Comment by rest515** [comment]
네네. "나만 볼 수 있습니다"보다 나은 설명문구가 있을까요?

**Comment by dongown** [comment]
처음에는 짧게 축약할 수 있는 설명문구를 생각해보았는데요, 예를 들면 다음과 같습니다.

- 나에게만 보입니다
- 공개되지 않습니다
- 노출되지 않아요
- 공개되지 않아요
- 나만의 기록

그런데 짧게 한다고 해도 4~5글자로 만들기는 어렵다는 것과 함께 우리가 왜 참여 데이터는 공개하는데 캠페인을 공개하지 않는지를 보여주면 좋겠다는 생각도 드네요. 

- 공개되지 않는 항목이니, 마음 편히 참여해보세요
- 나의 기록을 위한 항목(혹은 공간)입니다

**Comment by dongown** [comment]
처음에는 짧게 축약할 수 있는 설명문구를 생각해보았는데요, 예를 들면 다음과 같습니다.

- 나에게만 보입니다
- 공개되지 않습니다
- 노출되지 않아요
- 공개되지 않아요
- 나만의 기록

그런데 짧게 한다고 해도 4~5글자로 만들기는 어렵다는 것과 함께 우리가 왜 참여 데이터는 공개하는데 캠페인을 공개하지 않는지를 보여주면 좋겠다는 생각도 드네요. 

- 공개되지 않는 항목이니, 마음 편히 참여해보세요
- 나의 기록을 위한 항목(혹은 공간)입니다

**Comment by dongown** [comment]
현재 참여한 캠페인이 모든 사람들에게 보입니다.
로그인을 하고, 내 페이지를 갔을 때 나에게만 보이도록 합니다.

[로그인을 하지 않았을 때 들어간 1616 유저 페이지] https://campaigns.kr/users/1616 
![1616 유저 페이지](https://user-images.githubusercontent.com/72062336/178551587-16668d7d-48b8-49ba-b33f-d92564b521c7.png)

**Comment by dongown** [comment]
확인했습니다. 이상 없습니다 :)
