### ISSUE TITLE
[인물 페이지] 답변을 추가합니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#386]
인물 페이지 하단에 답변을 추가합니다.

답변
-
촉구 대상의 모든 답변을 최신순으로 나열합니다. 스크롤을 내릴 경우 다음 페이지로 넘길 수 있고, 다음 페이지로 갈 경우 답변만 노출되는 페이지로 이동합니다. 

답변은 사진, 이름 및 직책, 캠페인 명, 찬반 표시, 답변 내용이 표시되도록 합니다.
답변에서 '캠페인 명'이 잘 보이도록 배치합니다.
현재 답변 목록에서 이름과 답변 내용 사이에 ‘캠페인 명’에 대한 답변(링크 : 캠페인)'을 추가합니다.
스크롤을 내릴 경우 다음 페이지로 갈 수 있으며, 다음 페이지는 답변만 노출됩니다.

![답변 예시(안)](https://user-images.githubusercontent.com/72062336/178304923-3862f39a-5d9d-4586-90ae-40cbae1005ee.png)

**Comment by dongown** [comment]
답변 내용 형식을 조금 바꾸면 어떨까 싶습니다.
이전 지방선거 페이지에서도 어떤 캠페인에 대한 답변인지 헷갈린다는 이야기를 들었어요.
이름과 내용 사이에 <캠페인 명(링크)에 대한 답변입니다> 의 형태로 다음과 같이 하면 어떨까요?

**Comment by rest515** [comment]
반영하였습니다.

**Comment by dongown** [comment]
확인했습니다. 이상 없습니다 :)
