### ISSUE TITLE
[인물 페이지] 촉구 캠페인을 추가합니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#387]
인물 페이지 상단에 촉구 캠페인을 노출시킵니다.

캠페인
-
촉구 캠페인을 모아서 보여줍니다. 최근 촉구 캠페인 6개(2줄)를 노출하고 그 이상의 캠페인은 ‘더보기' 처리를 합니다. 오른쪽 상단에 '더보기'를 위치시킵니다.
'더보기'를 누를 경우 전체 촉구 캠페인 목록으로 연결됩니다.

**Comment by dongown** [comment]
촉구 캠페인이 자주 만들어지지는 않긴 해서 1줄도 괜찮을 것 같지만요,
'더 보기'를 누르지 않는다는 가정이 있다면 2줄 정도로 해서 한 페이지에 조금 더 풍성하게 담아봐도 좋겠다는 생각도 듭니다.

**Comment by rest515** [comment]
추가했습니다.

**Comment by rest515** [comment]
1. 새 캠페인 만들기는 일단 유지할께요. 오른쪽에는 액션 링크가 붙고.. 제목 다음 줄에는 검색이나 필터링 기능이 붙는 줄이거든요.
2. 순서는 바꾸었습니다.
3. 수정하였습니다.

**Comment by dongown** [comment]
1번 같은 경우는 나중에 추가적으로 기능이 붙을 수 있다는 말씀이시죠? 알겠습니다 :)

2,3번 모두 확인했습니다. 이상 없습니다~!
