### ISSUE TITLE
[인물 페이지] 조직/기관 페이지를 추가합니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#388]
빠띠 캠페인즈 > 인물 > 조직/기관 페이지

인물 페이지 상단의 조직/기관 목록 중 조직/기관을 클릭할 경우 조직/기관 페이지로 이동합니다.
조직/기관 페이지는 조직/기관 추가에서 적용한 slug입니다.
예 - https://campaigns.kr/agencies/assembly_20th%20

[조직/기관 페이지 구성]
프로필 : 로고/이름/캠페인 개수/소속된 인물 수
조직/기관 대상 캠페인 : 촉구 캠페인 목록
소속 인물 : 조직/기관에 포함된 인물. 인물을 클릭할 경우 '인물 개인 페이지'로 이동합니다.

**Comment by rest515** [comment]
바로 캠페인 시작하기는 조금 복잡하네요. 다음으로 미루면 좋겠습니다.
