### ISSUE TITLE
[운영툴] 사용하지 않는 촉구 대상 기관을 숨김처리할 수 있습니다.

### ISSUE THREAD

**Issue by rest515** [parti-coop/campaigns#390]

**Comment by dongown** [comment]
현재 10개 기관을 제외하고 모두 숨김처리를 했는데요,
인물 페이지에는 여전히 모든 기관이 노출되고 있습니다.

확인부탁드려요.


![인물 페이지](https://user-images.githubusercontent.com/72062336/178311202-fad59514-d940-4753-b324-c80ebab36135.png)

![기관 숨김 현황](https://user-images.githubusercontent.com/72062336/178311274-cef544b2-1c43-43be-b89c-dd8209f4d6f1.png)

**Comment by rest515** [comment]
처리하였습니다.

**Comment by dongown** [comment]
확인했습니다. 이상 없습니다 :)
