### ISSUE TITLE
[행동강령 추가] 하단 푸터에 행동강령을 추가합니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#394]
빠띠 캠페인즈 하단 푸터에 행동강령을 추가합니다. 이용약관 왼쪽에 추가합니다.
행동강령을 클릭할 경우 링크(https://coop.parti.xyz/front/posts/50490) 로 연결됩니다.

<img width="550" alt="캠페인즈 하단 푸터" src="https://user-images.githubusercontent.com/72062336/178315439-929f4439-b244-44c9-ad1c-dacdd1b1cc21.png">

**Comment by dongown** [comment]
이번주 수요일(7/13)까지 링크 추가해놓도록 하겠습니다.

한 가지 고민은 텍스트인데요, 정식 명칭은 '행동강령 및 운영정책'이지만 이 텍스트를 모두 옮길 수는 없다고 봅니다. 일반적으로는 운영정책을 많이 활용하지만 빠띠에서 행동강령 워크샵도 하는만큼 행동강령이라는 표현을 지금까지 많이 썼다는 생각이 들어 '행동강령'으로 하면 어떨까 싶네요.

**Comment by rest515** [comment]
네, <행동강령> 좋습니다.

**Comment by dongown** [comment]
@rest515 행동강령 링크 추가했습니다 :)

**Comment by dongown** [comment]
확인했습니다~! 이상 없습니다.
