### ISSUE TITLE
[어드민 개선] 인물을 쉽게 확인하고, 삭제할 수 있도록 합니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#401]
빠띠 캠페인즈 어드민에서 이메일이 없거나, 관련캠페인이 없는 인물을 확인하고 삭제할 수 있도록 합니다.

**Comment by dongown** [comment]
@rest515 현재 어드민 기능 추가해주신 사항 확인했습니다.
이메일이 없고, 관련캠페인이 0인 것을 '삭제대상'으로 볼 수 있도록 만들어주셨네요.
삭제해도 되는 인물인지 페이지별로 샘플링 통해서 확인해보도록 하겠습니다.

이전에 논의했을 때는 삭제도 어드민에서 진행해보자고 이야기를 했었는데요,
그렇다면 추가로 '인물을 선택해서 삭제할 수 있는 기능(전체 선택 가능)'이 필요합니다.
지금은 한명 한명 삭제를 클릭해야 하는 구조입니다.

**Comment by rest515** [comment]
우선 유형을 파악하고.. 디비에서 지우는 방법을 찾아볼까요. 계속 쓸 기능이 아니어서 개발하는건 지양하려고요.

**Comment by rest515** [comment]
DB에서 바로 작업할 수 있을 것 같네요. 유형을 파악해서 정리해 주세요.

**Comment by dongown** [comment]
네네 알겠습니다. 공론장 페이지 작업하면서 살짝 늦어지고 있는데요, 혹시 다음주 월요일(8/8)정도까지 파악해서 말씀드려도 작업 진행하시는 것에 지장이 없을까요? 이번 시즌이 8/12까지라 여쭤봅니다.

**Comment by dongown** [comment]
@rest515 '인물 - 삭제대상(https://campaigns.kr/admin/agents?filter=noinfo) 페이지'에 있는 목록을 페이지별로 몇 개씩 선택해서 확인해보았습니다. 이메일과 관련 캠페인이 모두 없는 유형을 삭제하면 되겠습니다. 이메일은 없는데 관련 캠페인이 있는 경우(태영호 https://campaigns.kr/agents/9483) 도 삭제대상 페이지에 포함되어 있는데 이러한 인물은 삭제하지 않습니다.

이메일과 관련 캠페인이 없는 인물들의 포지션이 모두 '제7대_지방선거_예비후보'로 등록되어 있는데요, 제7대 지방선거는 기관/조직은 없는 상황입니다. 혹시 7대 지방선거 때 관련된 활동을 했거나, 캠페인을 진행하셨었나요?(기억이 안 나실 것 같긴 합니다.. 너무 오래되어서...)

**Comment by rest515** [comment]
1차로 7대 지방선거 예비후보자들을 삭제했습니다. 이 작업은 시즌에서 빼내서 운영 작업으로 옮기면 어떨까요?

**Comment by dongown** [comment]
@rest515 인물과 기관/조직을 주기적으로 모니터링하면서 관리하자는 말씀이신거죠? 그 외에도 혹시 삭제할만한 인물이 있는지 확인해보구요.
