### ISSUE TITLE
[캠페인 사이드바 추가] 캠페인 페이지 오른쪽 사이드바에 캠페인 체크리스트를 추가합니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#402]
💡성공적인 캠페인을 위한 Tip
[ ] 프로필 설명에서 나에 대한 소개를 추가해주세요.
    > 프로필에서 자신 혹은 단체의 사진과 간략한 소개를 추가해보세요. 캠페인 페이지에 들어온 사람들이 캠페이너가 누구인지 알게 되면 더욱 신뢰감을 가지고 캠페인에 참여합니다.
[ ] 상세설정에서 필요한 참여자 정보를 확인해주세요.
    > 이메일, 연락처 등의 정보를 통해 캠페인 참여자들과 지속적으로 소통해보세요. 참여자 데이터를 활용하고 싶다면 ‘제 3자 동의'도 함께 체크해야 합니다.
[ ] 3명의 참가자를 모아주세요.
    > 참여자 3명부터 캠페인즈 메인 화면에 노출됩니다. 캠페인 URL을 공유해 지인에게 참여를 요청해보세요! 3명 정도의 마중물 참여가 없는 캠페인은 사람들의 자발적인 참여율이 매우 낮아집니다.
[ ] 적절한 이미지를 넣어주세요.
    > 이미지는 사람들의 시선을 쉽게 끌기 좋습니다. ‘관리’에서 커버이미지의 권장 사이즈를 확인해서 넣어보세요.
[ ] 사람들이 공감할 수 있도록 작성해주세요.
    > 가능하면 쉽고 흥미롭게 이야기를 풀어가는 방식으로 내용을 작성해보세요. 공감을 불러일으킬 수 있을 때 참여는 배가 됩니다.
[ ] 참여자에게 명확한 행동을 제안해주세요.
    > 캠페인을 클릭한 사람들이 무엇을 해야하는지 쉽게 알 수 있어야 참여하게 됩니다.
[ ] 적당한 길이로 내용을 작성해주세요.
    > 주로 모바일로 캠페인을 보기 때문에, 너무 긴 내용을 한번에 담기보다는 핵심 내용을 위주로 간결하게 작성하면 좋습니다.

**Comment by dongown** [comment]
@rest515 오른쪽 사이드바에 들어갈 캠페인 체크리스트를 작성해보았어요. 처음에는 체크리스트 내용 옆에 박스칸을 만들어 캠페이너가 직접 체크할 수 있도록 하자는 이야기까지 나왔는데요, 그냥 노출만 해도 큰 지장은 없을 듯합니다(체크할 수 있으면 좋긴 하겠네요)

캠페인 내용이 길지 않을 경우 사이드바가 내용보다 길어질 있겠다는 고민이 들긴 합니다. 세 가지 방법 중 하나를 해볼 수 있겠네요.

1. <💡성공적인 캠페인을 위한 Tip> 만 노출하고, 사이드바를 펼칠 수 있도록 한다. 펼친 뒤에는 전체 내용을 노출한다.
2. 메인 항목([ ] 프로필 설명에서 나에 대한 소개를 추가해주세요.)을 노출하고, 상세 설명(> 프로필에서 자신 혹은 단체의 사진과 간략한 소개를 추가해보세요.)은 펼쳐볼 수 있도록 한다.
3. 오른쪽 사이드바가 아닌 캠페인 설정 탭과 내용 사이에 팁 하나를 랜덤으로 노출시킨다.

**Comment by rest515** [comment]
두번째 팁의 "이메일, 연락처 등의 정보를 통해 캠페인 참여자들과 지속적으로 소통해보세요" 부분을 어떻게 하면 되는지 모호한 것 같습니다.

캠페인 소식을 전하라는 항목이 따로 들어가면 좋겠네요.

**Comment by dongown** [comment]
@rest515 이렇게 해보면 어떨까요?

[ ] 상세설정에서 필요한 참여자 정보를 확인해주세요.
> 참여한 사람들이 누구인지 확인하고 싶다면 이메일, 연락처 등을 적을 수 있도록 추가해보세요. 만약 참여자 데이처를 활용하고 싶다면 '제 3자 동의'를 체크해야 합니다.

그리고 캠페인 소식 부분은 체크리스트 가장 하단에 넣으면 어떨까 싶습니다.

[ ] 소식을 통해 참여자들과 소통해보세요.
> 소식에서 글을 작성하면 캠페인 참여자에게 자동으로 이메일이 발송됩니다. 캠페인의 진행상황을 공유하거나, 관련 정보를 전달하는 방식으로 참여자들과 소통해보세요. 소통이 있다면 우리의 연결성은 더욱 강화됩니다.

**Comment by rest515** [comment]
좋습니다.

**Comment by dongown** [comment]
@rest515 체크리스트 텍스트 수정과 항목 하나 추가하는 부분 확인부탁드려요. 이 부분만 반영되면 이번 시즌 일감은 끝입니다.

**Comment by dongown** [comment]
@rest515 소식 부분 메세지 다듬은 것과 링크가 반영되지 않은 듯 합니다. 

<소식을 통해 참여자들과 소통하세요.> 라고 되어있습니다.
