### ISSUE TITLE
[버그?] 투표 페이지에서 투표 게시물 등록이 되지 않습니다.

### ISSUE THREAD

**Issue by ramsci82** [parti-coop/campaigns#403]
깃헙에 직접 들어오는 건 오랜만이네요. 버그 제보 해도 되는 거겠지요? ^^;;

토픽/이슈 범주화도 되고 해서, 믹스에서 캠페인즈로 열린공론장 콘텐츠를 옮기려던 차인데, 투표 게시물 등록이 되지 않습니다. 

''옵션은 둘 이상이어야 합니다"라고 메세지가 계속 뜹니다.(첨부 사진 참조)

혹시나 또 제가 잘못하고 있는 걸까봐 여러 버전으로 진행해봤는데도 등록이 안되네요.

고쳐주시면 콘텐츠를 옮기는 작업에 들어가려 합니다!

![스크린샷 2022-07-27 오전 1 05 29(2)](https://user-images.githubusercontent.com/66588581/181055866-8c0aa97d-7af4-495c-81c8-49a2dfe75f9c.png)

**Comment by rest515** [comment]
투표 항목을 넣으셨을까요?

**Comment by ramsci82** [comment]
네, 두 개 이상 넣어 다회 시도해봤습니다. 혹시 제가 또 놓친게 있을까 싶었는데, 트리님도 안된다고 하시네요.

**Comment by ramsci82** [comment]
고쳐 주신 것인지 지금 들어가서 확인하니 잘 등록이 되네요! 작업을 시작해보도록 하겠습니다! 👍
