### ISSUE TITLE
[공론장 페이지] 토론 상세설정을 할 수 있도록 합니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#408]
토론 시작하기를 누르거나, 토론을 수정할 때 나타나는 상세설정을 만듭니다.

[상세설정 구성]
이슈(선택)
제목
설명

**Comment by dongown** [comment]
덧붙여, 게시글에 들어갔을 때 관리자는 '수정/삭제/상단고정걸기'가 가능하도록 하기로 했었는데 현재 '상단고정걸기'가 사라졌습니다. 확인부탁드려요.

<img width="500" alt="토론 게시글 상단 화면" src="https://user-images.githubusercontent.com/72062336/181065507-d861ffce-43df-4299-8bf1-a7a20c204e88.png">

**Comment by rest515** [comment]
저희가 고정걸기 기능을 쓰기로 했었나요? 필요없을 것 같다고 한 기억이 나서 삭제했거든요.

**Comment by rest515** [comment]
일단 버튼은 추가했는데요. 목록에선 아직 반영이 되진 않습니다. 나중에 필요할때 반영하면 어떨까 싶습니다.

**Comment by dongown** [comment]
네네 알겠습니다 :) 일단은 이렇게 마무리하면 될 것 같네요.
