### ISSUE TITLE
AS - 이슈를 선택한 투표도 해당되는 이슈 페이지에 나타나도록 합니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#411]
투표에서 이슈를 선택하고 저장을 할 경우 하단에 이슈가 나타나지만, 이슈를 클릭했을 때 투표 콘텐츠가 나타나지 않습니다.
이슈를 클릭했을 때 투표가 나타나도록 합니다.

현재 다른 투표는 이슈 페이지에 나타나지만 '[1년 빠른 초등학교 입학, 어떻게 생각하세요?](https://campaigns.kr/surveys/186)'는 [교육 공공성 이슈 페이지](https://campaigns.kr/issues/148)에 나타나지 않습니다.

[교육 공공성을 선택한 투표 페이지
<img width="782" alt="1년 빠른 초등학교 입학, 어떻게 생각하세요?" src="https://user-images.githubusercontent.com/72062336/182614099-6dc9c118-4d5f-487e-9a37-ae99aee47e40.png">

[교육 공공성 이슈 페이지]
<img width="761" alt="교육 공공성 이슈 페이지" src="https://user-images.githubusercontent.com/72062336/182614163-75d1797c-278e-46d2-a0a4-bf7f82a656d7.png">

**Comment by rest515** [comment]
정렬이 거꾸로 되어 있었네요. 수정했습니다.
