### ISSUE TITLE
[투표 콘텐츠 페이지] 투표 항목 표시 - 로그인하지 않는 사람도 투표 항목이 나타나도록 합니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#415]
현재 투표를 한 항목이 '로그인을 한 사람'만 나타납니다.
로그인을 하지 않는 사람도 투표 항목이 나타나도록 합니다.

[[투표 댓글 화면]](https://campaigns.kr/surveys/186)
<img width="1138" alt="투표 댓글 화면" src="https://user-images.githubusercontent.com/72062336/182619177-2df4e787-b039-414c-98a4-cdb73077b443.png">

**Comment by rest515** [comment]
로그인하지 않은 사람은 어디에 투표를 했는지 알수가 없어서 표시할 수 없습니다.

**Comment by dongown** [comment]
아, 네네 알겠습니다. 그러면 이슈는 닫아놓겠습니다.
