### ISSUE TITLE
[조직/기관 페이지 AS] 조직/기관 페이지에 관련없는 캠페인을 삭제합니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#417]
새로운 조직/조직 기관인 ['21대 기재위(22.06부터~)'](https://campaigns.kr/agencies/assembly_21th_finance_new)를 추가했는데요,
연관이 없는 캠페인이 21대 기재위(22.06부터~)에 함께 나타납니다.
연관이 없는 캠페인은 보이지 않도록 합니다. 현재 해당되는 캠페인은 ['협동조합의 성숙, 발전에 역행하는 기획재정부 조직개편(안)의 재고, 철회를 촉구합니다.'](https://campaigns.kr/campaigns/725)입니다.

[[참고 : 21대 기재위(22.06부터~) 수정 화면]](https://campaigns.kr/admin/agencies/assembly_21th_finance_new/edit)
<img width="1174" alt="21대 기재위(22.06부터~) 수정 화면" src="https://user-images.githubusercontent.com/72062336/182620664-5f4f5d31-f91a-46f9-9a4a-2a846e19a4a5.png">

[[참고 : 21대 기재위(22.06부터~) 화면]](https://campaigns.kr/agencies/assembly_21th_finance_new)
<img width="1163" alt="21대 기재위(22.06부터~) 화면" src="https://user-images.githubusercontent.com/72062336/182621309-9cffe343-958c-453c-9918-2e9b19e150b0.png">

**Comment by rest515** [comment]
"연관이 없는 캠페인은 보이지 않도록 합니다. 현재 해당되는 캠페인은"이라고 적어주셨는데..

연관이 없는 캠페인 = ['협동조합의 성숙, 발전에 역행하는 기획재정부 조직개편(안)의 재고, 철회를 촉구합니다.'](https://campaigns.kr/campaigns/725) 라는 의미일까요? 내용을 봐서는 거꾸로 같은데 확인해주세요.

**Comment by dongown** [comment]
@rest515 ['협동조합의 성숙, 발전에 역행하는 기획재정부 조직개편(안)의 재고, 철회를 촉구합니다.'](https://campaigns.kr/campaigns/725) 만 연관이 있는 캠페인입니다. 조직/기관을 새로 추가했는데, 다른 캠페인들이 갑자기 대상 캠페인들에 나타났습니다.

**Comment by dongown** [comment]
@rest515 현재 [어드민 조직/기관 목록](https://campaigns.kr/admin/agencies)에서 보여지는 캠페인의 개수와 전반적으로 많이 다른데요,
예를 들어 21대 기재위(22.06부터~) 는 여전히 캠페인이 10개라 나옵니다(물론 페이지에 들어가면 1개만 노출됩니다.)
그리고 [21대국회 국방위](https://campaigns.kr/agencies/assembly_21th_nd) 도 어드민에는 8개라 나오는데 실제 페이지로 들어가면 캠페인이 없네요(이전에는 있었던 것으로 기억해요)

큰 이슈는 없는 것이겠죠? 이전에 조직/기관별로 캠페인 개수를 정확히 알고 있지 않아 딱 비교하기가 쉽지 않네요.

<img width="1178" alt="스크린샷 2022-08-04 오후 1 59 08" src="https://user-images.githubusercontent.com/72062336/182766521-8c06ccc6-bae8-445a-b38e-726d3c381d0a.png">

**Comment by rest515** [comment]
운영툴도 고쳐야겠네요. 지금까진 기관의 관련 캠페인은 소속된 인물들과 관련된 캠페인을 모두 합산하는 방식이었습니다. 이게 여전히 필요할 것도 같아서 살려는 놨는데. 상세 페이지에선 직접 기관을 지정한 경우만 연결해 놨습니다.

**Comment by dongown** [comment]
네네 이해했습니다 :) 그러면 일단은 '관련 캠페인은 소속된 인물들과 관련된 캠페인을 모두 합산하는 방식'은 남겨놓아도 좋을 것 같아요.
운영툴 수정 없이 저희가 기억만 해두면 되지 않을까 싶네요.
