### ISSUE TITLE
[내 페이지 AS] SNS 회원가입 시 내 페이지에 들어갈 수 있도록 합니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#419]
페이스북으로 회원가입을 하고, 로그인을 했을 때 '내 페이지'를 누르면 다음과 같은 화면이 나타나며 내 페이지에 들어갈 수 없습니다.
참고로 페이스북 이메일 계정은 jay@parti.coop 이 아니라고 합니다.

[내 페이지 오류 화면]
<img width="735" alt="페이스북 회원가입 내 페이지 화면" src="https://user-images.githubusercontent.com/72062336/182627715-59d80eca-c97c-49e5-b4f4-a68e7a70bf1d.png">

**Comment by rest515** [comment]
jay@parti.coop으로 들어가지는게 이상하네요? 혹시 다른 분도 테스트해볼 수 있을까요?

**Comment by dongown** [comment]
다시 탈퇴하고 시도해보았는데 이상없이 진행되네요. 다른 크루들한테 한번 요청해서 확인해볼게요.

**Comment by dongown** [comment]
아직 이 부분은 확인해주실 분을 찾지 못했습니다😥
제가 다시 해볼 때는 이상은 없긴 해요.

**Comment by dongown** [comment]
일단 테스트 결과 이상은 없으니 이슈는 닫아놓을게요. 혹시 다시 발견되면 그때 오류 확인해보면 될 듯 합니다.
