### ISSUE TITLE
[투표 페이지 '내 글' AS] 내 글을 눌렀을 때 내가 작성한 댓글을 볼 수 있도록 합니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#421]
현재 투표 페이지 댓글 목록 상단에 '내 글'이 있습니다.
그러나 이를 클릭했을 때 아무런 변화가 나타나지 않습니다.
'내 글'을 클릭했을 때 내가 작성한 댓글만 볼 수 있도록 합니다.
'내 글'을 클릭한 이후에 '전체 보기'를 누르면 전체 댓글이 나타나도록 합니다.

[[댓글 목록 및 내 글 화면]](https://campaigns.kr/surveys/186)
<img width="1137" alt="댓글 목록 및 내 글 화면" src="https://user-images.githubusercontent.com/72062336/182634506-7d69c6ef-c143-493a-89e7-3411a13e838f.png">

**Comment by dongown** [comment]
@rest515 이 기능은 이렇게 수정하기보다는 당분간 숨겨놓으면 어떨까 싶기도 하네요. 댓글이 10개 이상 달린 투표들이 나타나기 시작하면 그 때 다시 기능을 넣어도 좋구요.

**Comment by rest515** [comment]
네네. 댓글 영역이 공통 컴포넌트화 되어 있는데 한번에 싹 고쳐야 할 것 같습니다. 수정 기능도 추가해야 하구요.

**Comment by rest515** [comment]
기능을 삭제해 두었습니다.

**Comment by dongown** [comment]
이 부분도 필요하다면 댓글 논의할 때 한번에 같이 논의하면 되겠네요. 확인했습니다 :)
