### ISSUE TITLE
[토픽 페이지] 토픽 페이지에서 토론과 투표를 노출합니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#423]
현재 '토픽 페이지에서 이슈를 클릭할 경우' 토론과 투표가 모두 노출됩니다.
그런데 '토픽'을 눌렀을 경우 토론만 노출됩니다.

예 - [교육 토픽](https://campaigns.kr/discussions?agenda_id=23)  / [교육 -> 교육 공공성 이슈](https://campaigns.kr/issues/148)
[교육 토픽 화면]
<img width="600" alt="교육 토픽 화면" src="https://user-images.githubusercontent.com/72062336/182640026-2292bd9b-e438-48ee-8f10-d944d65e4591.png">
[교육 공공성 이슈 화면]
<img width="600" alt="교육 공공성 이슈 화면" src="https://user-images.githubusercontent.com/72062336/182640109-937d4cb9-a75d-45e0-9a4b-a425f3d913a8.png">

**Comment by dongown** [comment]
토픽을 보다가 이슈로 들어갔을 때 갑자기 투표가 등장하는 부분이 어색하긴 합니다.

이 부분은 일부러 이렇게 설정을 의도하신 것일까요?

토픽 페이지는 토론글에서 연결되기에 토론만 노출되고,
이슈 페이지는 토론과 투표 모두에서 연결되기에 토론과 투표를 모두 노출하는 방향으로 설정하신 것이 맞을지 확인해보고자 남깁니다.

**Comment by rest515** [comment]
현재 이슈별로 토론글이 충분치 않다는 지적 때문에. 토픽 페이지를 임시로 만든건데요. 앞으로는 토픽 페이지가 없어야 하지 않을까 싶습니다. 토픽-이슈-글,캠페인,투표로 유지하면 뭔가 개념의 깊이가 너무 복잡해지더라구요.

**Comment by dongown** [comment]
좋습니다. 지금은 너무 단계가 많아보이네요 :)
조금 더 쌓인 이후에 말씀하신 것처럼 수정하면 될 것 같아요.
