### ISSUE TITLE
[소식] 소식이 최신순으로 나타나도록 합니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#425]
현재 소식 목록 글이 최신순이 아닌 오래된 순서로 나타납니다.
'소식' 페이지에 들어갔을 때 가장 최신 글이 먼저 보이도록 순서를 조정합니다.

[소식 페이지 예시
](https://campaigns.kr/campaigns/707/stories) 와 가장 최신에 올라온 [소식 예시](https://campaigns.kr/stories/475)
<img width="771" alt="소식 페이지" src="https://user-images.githubusercontent.com/72062336/182736569-828e1d22-5a0a-429c-80e9-d81aba1674a9.png">

**Comment by dongown** [comment]
@rest515 배포 하시는 동안 작성했던 것인데요, 혹시 이 부분까지 배포가 된 것일까요?
작업 완료처리 되어있지만, 아직 반영되지 않은 것 같아 여쭤봅니다.

**Comment by dongown** [comment]
이전에는 시스님이 작업해주시고, 배포까지 완료한 뒤에 '작업 완료'를 체크해주시면 제가 테스트 하고 이상 없으면 '배포 완료'로, 이상 있으면 '작업 중'으로 상태 변경을 했었습니다. 이름상으로 보았을 때 살짝 어색하긴 하네요. 현재 작동 검토 중도 있는데 이 상태는 쓰지 않고 있기도 하구요.

제안주신 것처럼 시스님께서 작업하실 때는 '작업 중', 배포 완료인 것은 '배포 완료', 이후에 제가 테스트하고 이상이 없으면 '작업 완료(+이슈 클로즈)'로 두면 어떨까 싶네요. 이상이 없으면 다시 '작업 중'으로 변경하구요.

더 세분화시킨다면 배포 완료 상태를 '작동 검토 중'으로 바꾸고 테스트한 이후에 '작업 완료'로 하는 등의 과정을 넣어볼 수 있겠지만 그렇게까지는 필요없지 않을까 싶구요.

**Comment by rest515** [comment]
네네 좋습니다. 오늘부커 그렇게 써 보죠.
