### ISSUE TITLE
[투표/토론] 투표와 토론 콘텐츠에 공유 이미지를 추가합니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#427]
[카카오톡 공유]
현재 투표 콘텐츠는 카카오톡에서 공유를 했을 때 아무 이미지가 없는 빈 화면으로 나타나고,
토론 콘텐츠는 '빠띠 캠페인즈' 로고가 나타납니다.

투표 콘텐츠는 '대표 이미지'가 나타나도록 하고,
토론 콘텐츠는 '이미지가 있을 경우 첫 번째 이미지'가 나타나도록 합니다.

[투표 콘텐츠 카카오톡 공유 사진]
![투표 콘텐츠 카카오톡 공유 사진](https://user-images.githubusercontent.com/72062336/182993965-42004c1f-c611-45c7-93ab-08b712e40cf7.png)
[토론 콘텐츠 카카오톡 공유 사진]
![토론 콘텐츠 카카오톡 공유 사진](https://user-images.githubusercontent.com/72062336/182994446-426c9c2e-396d-442a-881b-8cde735adf85.png)

[소셜 공유]
현재 투표 콘텐츠는 SNS에서 공유를 했을 때 '이슈 이미지'가 나타나고,
토론 콘텐츠는 '빠띠 캠페인즈' 로고가 나타납니다.

투표 콘텐츠는 '대표 이미지'가 나타나도록 하고,
토론 콘텐츠는 '이미지가 있을 경우 첫 번째 이미지'가 나타나도록 합니다.

[투표 콘텐츠 페이스북 공유 사진]
![투표 콘텐츠 페이스북 공유 사진](https://user-images.githubusercontent.com/72062336/182994270-a2c71188-9669-471e-bc6b-1dead124773b.png)
[토론 콘텐츠 페이스북 공유 사진]
![토론 콘텐츠 페이스북 공유 사진](https://user-images.githubusercontent.com/72062336/182994604-198ef081-4936-4257-9f14-d3797618c267.png)

**Comment by dongown** [comment]
@rest515 소셜 공유/카카오톡 공유 관련되어서 의견 남겨놓았어요.

투표에는 '대표 이미지 설정'이 있기 때문에 대표 이미지가 나타나는 방식으로,
토론에는 이미지를 따로 설정하는 항목이 없기 때문에 이미지가 있으면 이미지를 보여주는 방식으로 일단 진행하면 어떨까 싶습니다.

혹은 토론에는 이미지가 없을 경우 '이슈의 이미지'가 나타나는 것도 하나의 방법이라고 생각이 들구요.

**Comment by ramsci82** [comment]
네, 좋네요. 트리님 제안대로 수정되면 좋을 것 같습니다.

**Comment by dongown** [comment]
@rest515 투표는 수정 완료되었습니다. 그런데 토론은 아직 적용되지 않은 것 같아요. 확인부탁드려요.
참고로 조금 더 말씀드리자면 토론을 만들 때는 '이미지를 에디터로 삽입하는 것' 외에는 따로 이미지를 설정하는 항목이 없습니다.

**Comment by rest515** [comment]
네. 그래서 토론에는 일단 이미지를 적용하지 않고 기본 이미지가 나오도록 해두었습니다.

**Comment by dongown** [comment]
아, 알겠습니다 :)

이후에 토론 콘텐츠가 많아지고 공유가 계속된다면 그때 다시 방법을 고민해보면 되겠네요.
