### ISSUE TITLE
투표 작성시에 이슈를 구독한 사용자들에게 메일로 알립니다

### ISSUE THREAD

**Issue by rest515** [parti-coop/campaigns#428]

**Comment by dongown** [comment]
정상적으로 작동합니다 :)

**Comment by dongown** [comment]
@rest515 현재 캠페인,토론에는 작동하지만 '토론'은 작동하지 않습니다. 혹시 토론은 당분간은 반영할 계획이 없으신 것일까요!?

**Comment by rest515** [comment]
투표와 캠페인에 비해서 토론은 너무 많이 올라올 것 같아서요. 아직은 아니지만, 토론글은 자주 올라오는게 바람직하기도 하고요. 어떻게 생각하시나요?

**Comment by dongown** [comment]
투표보다 토론이 더 낮은 장벽으로 보자는 말씀이신거죠? 그런 관점이라면 동의합니다.
그런데 개인적으로는 토론과 투표가 동일한 장벽으로 느껴지긴 합니다. 확 차이점이 보이지는 않는 것 같아요.
물론 다른 플랫폼들을 생각하면 토론은 이슈를 다루는 자유게시판같기에 장벽이 낮긴 합니다. 
이 부분이 저희가 풀어야 할 숙제겠네요.
