### ISSUE TITLE
[참여 현황 AS] 로그인을 하고 캠페인에 참여한 사람들의 오른쪽 참여 현황에 닉네임이 노출되도록 합니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#432]
현재 실명 입력 여부를 체크하지 않고 진행되는 캠페인을 '로그인을 한 유저'가 참여할 때 오른쪽 참여자 현황에서 이름이 노출되지 않습니다.
로그인을 하고, 참여를 할 경우 유저의 닉네임이 노출되어 <'닉네임'님이 참여(추모)하였습니다>가 나타나도록 합니다.

[[예시 화면(링크)](https://campaigns.kr/campaigns/727)]
추모 참여에는 joe98님이 로그인을 하고 참여했지만 오른쪽 추모 현황에서는 <님이 추모하였습니다> 라고 나옵니다
![예시 화면](https://user-images.githubusercontent.com/72062336/183800147-08729a85-d569-4567-af22-e9dd6661c740.png)

**Comment by dongown** [comment]
@rest515 배포를 쉬어가자고 했었는데, 하나 발견된 사항이 있어 우선 남겨놓습니다.

**Comment by rest515** [comment]
네네. 버그는 계속 고쳐야죠.

**Comment by dongown** [comment]
작업해주신 것 확인했습니다 :)
