### ISSUE TITLE
[어드민 개선] 회원 목록을 다운받지 않아도 확인할 수 있습니다.

### ISSUE THREAD

**Issue by dongown** [parti-coop/campaigns#433]
현재 캠페인즈 어드민(https://campaigns.kr/admin) 에서 회원 목록을 확인하기 위해서는 '회원 이메일 다운로드'를 통해 엑셀 파일을 다운받아야합니다.
엑셀 파일로 다운받지 않아도 회원 목록을 리스트업해서 볼 수 있도록 합니다.

노출되어야 하는 목록은 다음과 같습니다.
* 가입 날짜
* 회원 닉네임
* 이메일
* 참여 캠페인 횟수

**Comment by dongown** [comment]
@rest515 님 이제 캠페인즈 뉴스레터도 계속 발행하고, MAU도 체크하고있는만큼 캠페인 가입자도 챙겨보면 좋을 것 같아요(가입자분들께 뉴스레터도 발송해야 합니다).
그런데 지금 어드민에서는 회원 목록을 다운받아야만 확인할 수 있고, 이메일과 닉네임만 노출됩니다.

혹시 페이지에서 확인할 수 있도록 할 수 있을까요? 예를 들어 최근 사이에 가입자가 좀 많이 증가했는데 전혀 추적을 못하고 있었네요.
여전히 회원 목록은 다운받을 수 있도록 하되, 페이지 자체에서 확인할 수 있으면 합니다(가입 날짜, 닉네임, 이메일 노출). 가능하다면 참여 캠페인 횟수도 보여주면 좋겠구요.

**Comment by rest515** [comment]
네네. 대신 개인정보인지라 조회가 가능한 사람을 엄격하게 관리해야 합니다. 일단 운영자를 팀원으로만 다시 추려보시죠.

**Comment by dongown** [comment]
이전에 한번 운영자를 정리했던 터라 현재 운영자는 팀원으로만 되어있습니다(생생이, 항경이 등은 람시님이에요)

**Comment by dongown** [comment]
@rest515 어드민 페이지 회원 목록의 수와 회원 이메일 다운로드에서 나오는 숫자가 다른데요, 혹시 이유가 있을까요?

**Comment by rest515** [comment]
다운로드하는 데이터는 이메일이 있는 회원만 대상이 됩니다. 소셜 로그인의 경우 회원 가입시에 이메일을 못 가져오기도 하거든요.

**Comment by dongown** [comment]
같은 소셜 로그인이라도 이메일을 못 가져오는 경우가 있군요. 네네 알겠습니다 :)
