### ISSUE TITLE
팻말들기의 UX를 좌우 이단 구성으로 나누어 왼편엔 본문을 오른편엔 메시지를 보이면 어떨까요?

### ISSUE THREAD

**Issue by dalikim** [parti-coop/campaigns#50]
https://campaigns.kr/campaigns/190/pickets

지금은 메시지가 다양하고 많구나가 경험을 하게 되는데요. 이 것도 중요하지만, 올라온 팻말(목소리) 하나하나에 집중하게 만들어 보면 어떨까 싶어요.

어느 정도 좌우가 넓은 모니터에선 이단 구성으로 왼편과 오른편을 나누고요. 오른편으로만 메시지가 올라오게하면 몇 개 안보이니까 더 집중할 수 있을 듯해요. 부수적으론 캠페이너의 메시지도 붙박이가 되어 좋을 것 같아요.

**Comment by gjkimpam** [comment]
카드뉴스 내용이 세로로 길게 펼쳐지는군요. 
2단 구성보다는 카드뉴스가 노출되기 전에 팻말들기로 점프할 수 있는 **버튼**이 있는 것이 더 좋을 것 같아요. 

2단 구성으로 하게되면 한 화면에 너무 많은 정보(카드뉴스+팻말들기)가 동시에 노출되지 않나 싶습니다.

**Comment by dalikim** [comment]
@gjkimpam 두 개 정보가 아닌 하나의 맥락인데(캠페인의 맥락과 그 맥락에서 나오는 캠페인 참여자의 발화) 그게 한 번에 보이는게 왜 부담스러운지 모르겠네요. 차라리 사이드 바이 사이드로 나오는게 더 읽기 쉽지 않으려나 싶기도 합니다.

정말 부담스럽다면 차라리 카드뉴스 보다 팻말이 더 중요하다 생각해요. 뒤집으면 어떨까요?
